import { useRef, useState } from "react";
import "./Hero.css";
import { useGetSearchSuggestion } from "../../hooks/useGetSearchSuggestion";
import SearchSuggestions from "../SearchSuggestions";

const Hero = ({ banner = null }) => {
  const userInputRef = useRef(null);
  const [userInput, setUserInput] = useState("");

  // const { searchSuggestions } = useGetSearchSuggestion(userInput);

  // const searchInputUpdateRef = useRef(null);
  let searchInputUpdate;

  const submitHandler = (e) => {
    e.preventDefault();
  };

  const inputChangeHandler = (e) => {
    clearTimeout(searchInputUpdate);

    searchInputUpdate = setTimeout(() => {
      setUserInput(e.target.value);
    }, 1000);
  };

  console.log(searchSuggestions);

  return (
    <div className="hero-container wrapper-full">
      <div>{banner ? banner : null}</div>
      {/* <div className="hero-form-wrapper">
        <div className="hero-form">
          <form action="" onSubmit={submitHandler}>
            <div className="form-control">
              <input
                type="text"
                placeholder="Movies or TV shows"
                ref={userInputRef}
                onChange={inputChangeHandler}
              />
              <button>Search</button>
            </div>
          </form>
          <div className="search-suggestion-container">
            <SearchSuggestions data={searchSuggestions} />
          </div>
        </div>
      </div> */}
    </div>
  );
};

export default Hero;

const searchSuggestions = [
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    genre_ids: [35],
    id: 1668,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    popularity: 522.116,
    poster_path: "/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg",
    first_air_date: "1994-09-22",
    name: "Friends",
    vote_average: 8.441,
    vote_count: 7534,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/oJxLvh3ku9Ad8Axpm73DL45o1hw.jpg",
    genre_ids: [16, 35, 10765, 10762],
    id: 33765,
    origin_country: ["CA", "US"],
    original_language: "en",
    original_name: "My Little Pony: Friendship Is Magic",
    overview:
      "Journey to the enchanted land of Equestria, where unicorn Twilight Sparkle and her pals have adventures and learn valuable lessons about friendship.",
    popularity: 211.814,
    poster_path: "/fwW7WgJIjhBsnzk87Gyh6g9187m.jpg",
    first_air_date: "2010-10-10",
    name: "My Little Pony: Friendship Is Magic",
    vote_average: 8.1,
    vote_count: 596,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/7CvmnHAVxhDbYE7jPp0PbKunqqs.jpg",
    genre_ids: [10762, 16, 35],
    id: 127635,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Marvel's Spidey and His Amazing Friends",
    overview:
      "Follow Peter Parker, Gwen Stacy and Miles Morales and their adventures as the young heroes team up with Hulk, Ms. Marvel and Black Panther to defeat foes like Rhino, Doc Ock and Green Goblin and learn that teamwork is the best way to save the day.",
    popularity: 344.537,
    poster_path: "/etO5jDS5WgR4Y1lTyXhQcilJ6u2.jpg",
    first_air_date: "2021-08-06",
    name: "Marvel's Spidey and His Amazing Friends",
    vote_average: 7.3,
    vote_count: 227,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/Arl6Ylw80vsLa1zBxintk7zsIvT.jpg",
    genre_ids: [16, 28, 12, 35, 14],
    id: 290271,
    original_language: "ja",
    original_title: "ONE PIECE “3D2Y” エースの死を越えて! ルフィ仲間との誓い",
    overview:
      "The special takes place during the two year before the Straw Hats reunite on Sabody.  Luffy is currently in Rusukaina training to get stronger to take on the New World. However the training  is interrupted when Hancock's sisters, Marigold and Sandersonia, are kidnapped by the Byrnndi World,  a pirate who was locked away on Level 6 of Impel Down but escaped during Luffy's invasion to save Ace,  in order to lure Hancock to him and use her as a hostage against the World Government due to her  Shichibukai status. Thus Luffy and Hancock head off to confront him and save Hancock's sisters.",
    popularity: 49.535,
    poster_path: "/caUI7YlhVXykFWQ7Ul7RQ2wQRpv.jpg",
    release_date: "2014-12-31",
    title:
      "One Piece \"3D2Y\": Overcome Ace's Death! Luffy's Vow to his Friends",
    video: false,
    vote_average: 7,
    vote_count: 159,
  },
  {
    adult: false,
    backdrop_path: "/iMh5wkmPYgT39iL8VwFRkz82wdk.jpg",
    genre_ids: [16, 35],
    id: 60730,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "僕は友達が少ない",
    overview:
      "Kodaka Hasegawa has just transferred to St. Chronica's Academy and he's having a hard time making friends. With his naturally blond hair and fierce looking eyes, people constantly mistake him for a delinquent. One day, he runs into his bad-tempered loner of a classmate, Yozora, while she's talking to her imaginary friend, Tomo. Since neither of them have any friends, they decide to form a club and start recruiting some. Little by little, lonely classmates join their club to learn how to build friendships through cooking together, playing games, and other group activities. But, with so many misfits, will the club members really be able to get along?",
    popularity: 63.451,
    poster_path: "/c4zXDKYM3HQicLpqfGmZ3A6XvVN.jpg",
    first_air_date: "2011-10-07",
    name: "Haganai: I Don't Have Many Friends",
    vote_average: 7.672,
    vote_count: 131,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/wNYUv8u5Z0AI4dkyxGyet7eLEWm.jpg",
    genre_ids: [18],
    id: 945675,
    original_language: "zh",
    original_title: "一周的朋友",
    overview:
      "A high school student suffers from a strange amnesia, causing her memories to only last a week. After she befriends a new student, his kindness and persistence make her gradually open up.",
    popularity: 62.149,
    poster_path: "/wjYcNLVwFpSAGAPKgo0NIwhfWJS.jpg",
    release_date: "2022-06-18",
    title: "One Week Friends",
    video: false,
    vote_average: 5.7,
    vote_count: 112,
  },
  {
    adult: false,
    backdrop_path: "/leNZUBCvou9K8cRoTYnTq1Vu9O4.jpg",
    genre_ids: [35, 10751, 10765],
    id: 62783,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Best Friends Whenever",
    overview:
      "When their aspiring scientist friend Barry's invention goes awry, best friends Shelby and Cyd gain the power to leap forward and backward in time whenever they want – and sometimes when they don't. Now, they experience the twists and turns of friendship and must decide between fixing mistakes in the past or catching a glimpse of the future. While Barry and his assistant, Naldo, try to figure out how to replicate time travel for themselves, Cyd and Shelby use their newfound power to navigate high school life and Shelby's mischievous twin brothers, Bret and Chet.",
    popularity: 50.533,
    poster_path: "/euWwJsDLPzfPny96UrbD13XOFSz.jpg",
    first_air_date: "2015-06-26",
    name: "Best Friends Whenever",
    vote_average: 8.1,
    vote_count: 81,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/uELCMpKxSXqKN47iOUTjJmJD57g.jpg",
    genre_ids: [16, 10751],
    id: 1166714,
    original_language: "en",
    original_title: "Mickey and Friends: Trick or Treats",
    overview:
      "Mickey, Minnie, Goofy, Donald and Daisy are trick-or-treating when Donald spies the spookiest mansion he’s ever seen and assumes it has the best treats. After he convinces his friends to risk a visit, the owner, Witch Hazel, casts a spell that turns them into their costumes.",
    popularity: 29.734,
    poster_path: "/5Gz3k1TqeAxL5M47XZzjltxQrMb.jpg",
    release_date: "2023-10-01",
    title: "Mickey and Friends: Trick or Treats",
    video: false,
    vote_average: 7.016,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: "/jT7GMt5DH4A3Bbq55mwgEjq6n8o.jpg",
    genre_ids: [10751, 18, 35],
    id: 108248,
    original_language: "ta",
    original_title: "Friends",
    overview:
      "A man values his best friend more than anything else in the world. One day he confesses a dark secret from their childhood to his wife, which is overheard by another. Once the secret gets out, the friendship is destroyed.",
    popularity: 6.339,
    poster_path: "/s7YLtazr7adX2YVqhHYSOeZt0qb.jpg",
    release_date: "2001-01-14",
    title: "Friends",
    video: false,
    vote_average: 6.907,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: "/q38iwBEFZtwOHazJC77zcAMqLJP.jpg",
    genre_ids: [18, 35],
    id: 9777,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends with Benefits",
    overview:
      "Revolving around a group of twentysomething singles as they navigate the difficult, sometimes rewarding, often confusing world of dating. Loyal and devoted to one another, these friends are never too busy to help a member of the group who might be in need. In fact, their companionship often extends into a more intimate setting - the bedroom.",
    popularity: 23.988,
    poster_path: "/1VWVTX4NRsfpo5MUdVVGMpU0XYl.jpg",
    first_air_date: "2011-08-05",
    name: "Friends with Benefits",
    vote_average: 6.5,
    vote_count: 26,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/fLhUNR2eEF1XEMBbiVuM3eOR1ME.jpg",
    genre_ids: [16, 10762, 10751],
    id: 87547,
    origin_country: ["DK"],
    original_language: "en",
    original_name: "LEGO Friends: Girls on a Mission",
    overview:
      "Meet Andrea, Mia, Emma, Olivia and Stephanie. They're five best friends. And they're on a heroic mission: to save Heartlake City from wily swindlers.",
    popularity: 29.763,
    poster_path: "/ucWzrdR7Ac4WVzx6FMFRNukNUqe.jpg",
    first_air_date: "2018-03-16",
    name: "LEGO Friends: Girls on a Mission",
    vote_average: 6.3,
    vote_count: 21,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/8kYHyiA4aMq7ow5wFoXeh1xg8Gj.jpg",
    genre_ids: [18, 10749],
    id: 4156,
    original_language: "en",
    original_title: "Friends",
    overview:
      "Paul, a rich English boy, and Michelle, an orphaned French girl, run away from home to a remote beach. Living on their own, their friendship grows into love.",
    popularity: 5.423,
    poster_path: "/oaNJNddADomFR97gr3SsY6xVUuU.jpg",
    release_date: "1971-03-24",
    title: "Friends",
    video: false,
    vote_average: 6,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/yLLRJwHlRwADEojNwVhqAxSH8hh.jpg",
    genre_ids: [16, 35, 10762],
    id: 81425,
    origin_country: ["AT", "CY", "US", "TH"],
    original_language: "en",
    original_name: "Talking Tom and Friends",
    overview:
      "Armed with technological gear, great ideas and an unfailing sense of humour, Talking Tom and his friends are on a mission to reach stardom at all costs.",
    popularity: 121.588,
    poster_path: "/u6We7ht3z8bSIaUF8P7DEwopOPi.jpg",
    first_air_date: "2014-12-23",
    name: "Talking Tom and Friends",
    vote_average: 7.4,
    vote_count: 14,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/8Q6gV88DG9twlQtptqdDecDoxcN.jpg",
    genre_ids: [16, 35, 10751, 10762],
    id: 67431,
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Turma da Mônica",
    overview:
      "Monica, the leader of the crew and 'ruler of the street,' is a little girl with a strong personality, not one to overlook any insult. She absolutely loves her stuffed bunny, Samson, and takes him with her everywhere. Jimmy Five, one of her best friends, is a smart kid, but he's always provoking her. Maggy is Monica's best friend and a super cute girl, who is always eating watermelons. To complete the show's main quartet, enter Smudge, a skillful boy who is terrified of water.",
    popularity: 164.854,
    poster_path: "/xMibNLtAiLeDltSgfRmawFbtFzL.jpg",
    first_air_date: "1986-09-20",
    name: "Monica & Friends",
    vote_average: 7.8,
    vote_count: 12,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 196924,
    original_language: "en",
    original_title: "Friends",
    overview:
      "The beginning of the end of the apartheid era in South Africa is seen through the perspectives of three female friends: Sophie, who is of English descent; Aninka, who is an Afrikaner; and Thoko, who is black.",
    popularity: 1.259,
    poster_path: "/dZB6ny9nGD56crinf4hfeVFTZ2E.jpg",
    release_date: "1993-05-26",
    title: "Friends",
    video: false,
    vote_average: 5.5,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/wKJYYP4cX51Z7FWhFaUWmPVFGk1.jpg",
    genre_ids: [16, 35, 18],
    id: 72508,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "コンビニカレシ",
    overview:
      "Six high school boys hang out at a local convenience store where they talk about their daily lives. Haruki Mishima and Towa Honda are first year students looking forward to the high school experience. Alongside them, there’s Nasa Sanagi, the only member of the cooking research club. Natsu Asumi is a loner but has third year students, Mikado Nakajima and Masamune Sakurakoji, looking out for him.",
    popularity: 59.419,
    poster_path: "/lbZS7fyGP9LO8BqP8K6Z1UACmpl.jpg",
    first_air_date: "2017-07-07",
    name: "Convenience Store Boy Friends",
    vote_average: 7.8,
    vote_count: 10,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/i7f90jzCPDBJHf5bFbU9Ot2zSz.jpg",
    genre_ids: [37, 10749],
    id: 193838,
    original_language: "en",
    original_title: "Friends",
    overview: "The orphan Dora is courted by two different gold miners.",
    popularity: 0.849,
    poster_path: "/37P4dH2JCnbdObNBb79erJI8pzF.jpg",
    release_date: "1912-09-22",
    title: "Friends",
    video: false,
    vote_average: 5.375,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/wNTUNmA2hRgHf9yAG5vNPfQeAp.jpg",
    genre_ids: [16, 14, 12],
    id: 550104,
    original_language: "ja",
    original_title: "映画 妖怪ウォッチ FOREVER FRIENDS",
    overview:
      "Fifth Yo-kai Watch film. A yokai known as surinaki has escaped his sell and is causing trouble through out the yokai world Yasha Enma and Enma King Shien must stop him from destroying everything and stop Enma king Shein from turning to the Darkside.",
    popularity: 5.449,
    poster_path: "/9og4mdprkXaFyMtAjWZOCp4nE4f.jpg",
    release_date: "2018-12-14",
    title: "Yo-kai Watch: Forever Friends",
    video: false,
    vote_average: 7.3,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [16, 10759],
    id: 14042,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Super Friends",
    overview: "",
    popularity: 100.044,
    poster_path: null,
    first_air_date: "1973-09-08",
    name: "Super Friends",
    vote_average: 7.1,
    vote_count: 5,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/whQkcYHHd4djIiICHx1Vjv1Zy4o.jpg",
    genre_ids: [16],
    id: 10927,
    origin_country: ["US", "GB"],
    original_language: "sv",
    original_name: "De tre vännerna och Jerry",
    overview:
      "The Three Friends and Jerry is an animated television series which aired in the United States on Fox Family, Nickelodeon in the UK and Latin America and TG4 in Ireland. A Swedish/British co-production, the series was created by Magnus Carlsson and produced by Happy Life Productions and TV Loonland.",
    popularity: 80.319,
    poster_path: "/omUvnpqzmUIZ1Ica04mZXY48uev.jpg",
    first_air_date: "1999-01-22",
    name: "The Three Friends and Jerry",
    vote_average: 5.6,
    vote_count: 5,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/1eG5oa7hGKBVvhof9A3WNxC4YAx.jpg",
    genre_ids: [10749],
    id: 1016007,
    original_language: "ko",
    original_title: "빚에 팔려온 친구아내",
    overview:
      "Kim Hak-cheol is a trashy husband who sends his wife Jin Joo-hee to his friend Kang Min-hyeok as a housekeeper due to gambling debts. He visits his wife once in a while and steals money. He borrows money from Min-hyeok, a golden spooner who is Hak-cheol's friend, on the condition that Joo-hee is sent as a housekeeper. Min-hyeok is kind to his friend's wife, Joo-hee. Over time, the true colors begin to emerge. Meanwhile, Min-hyeok's wife, Nam Gyoo-ri, lives together with them without knowing anything about Joo-hee.",
    popularity: 9.868,
    poster_path: "/13LzYe1lpSUUjTx9AENh61I1DMl.jpg",
    release_date: "2022-06-30",
    title: "A Friend's Wife Sold in Debt",
    video: false,
    vote_average: 5.833,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/yVIudr5ZNtFvomu6CdFGKAa3njk.jpg",
    genre_ids: [35, 18, 10766],
    id: 36062,
    origin_country: ["NL"],
    original_language: "nl",
    original_name: "SpangaS",
    overview:
      "Best Friends follows the life of a group of friends at their high school ‘Spangalis College’. Inside and outside of school exciting and challenging experiences take place. Growing up is never easy; every character has its own, unique story of love, friendship, loneliness, sorrow, discovery. There is drama and joy in school, family, teachers, parents, divorce, bullying, and always dreams for the future.",
    popularity: 796.568,
    poster_path: "/2bH7QQ7WQfnbt1CWiX8BE5E2V4t.jpg",
    first_air_date: "2007-09-03",
    name: "Best Friends",
    vote_average: 4,
    vote_count: 4,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 44333,
    origin_country: [],
    original_language: "en",
    original_name: "Carol Burnett and Friends",
    overview:
      "Carol Burnett and Friends was a syndicated, truncated version of The Carol Burnett Show, showing only the sketches.The show star's Carol Burnett and co-star's Tim Conway and Harvey Korman, Carol Burnett's related shows: The Carol Burnett Show Carol Burnett and Company The Carol Burnett Show (1991) Carol & Company",
    popularity: 234.363,
    poster_path: null,
    first_air_date: "1972-10-01",
    name: "Carol Burnett and Friends",
    vote_average: 4.8,
    vote_count: 2,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 20813,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Friends",
    overview:
      "Friends is a short-lived kids-oriented drama that aired in the spring of 1979. The series, which was produced by Aaron Spelling and aired on ABC, starred Charlie Aiken, Jill Whelan, and Jarrod Johnson as three Southern Californian 11-year-olds. Karen Morrow also appeared. Only five one-hour episodes were produced before the series was cancelled.",
    popularity: 23.335,
    poster_path: "/ogRWiG361aZsRe0M35iou9E7nq6.jpg",
    first_air_date: "1979-03-25",
    name: "Friends",
    vote_average: 5,
    vote_count: 1,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/w0D1MH6ZwCqqnx3KEEm0lRv7PfT.jpg",
    genre_ids: [10766, 18, 10751],
    id: 12703,
    origin_country: ["MX", "US"],
    original_language: "es",
    original_name: "Amigos x Siempre",
    overview:
      "The story is set at a prestigious, but rigid and repressive school called Instituto Vidal. Its strict owner, Julia Vidal, was once kind but has now turned into a bitter woman following the death of her husband and her daughter, Lauriel. Her granddaughter, Ana, a very sweet and intelligent 10 year old, also has been affected by the death: She has been rendered virtually speechless by the trauma, though she expresses herself through music and possesses an extraordinary ability to move objects with her mind. Ana's unscrupulous father, Francisco Capistrán, however, has taken advantage of the situation to try to steal Julia's school. The timely arrival of Ana's uncle, Salvador, Amanda and her adopted son changes everything. Ana’s sad and lonely life takes an unexpected turn for the better and she regains her joy in a series of adventures bursting with humor, excitement, music and thrilling surprises.",
    popularity: 216.424,
    poster_path: "/peDdHSj903FEMBBMEqx9DuCaBvw.jpg",
    first_air_date: "2000-01-10",
    name: "Friends 4 Ever",
    vote_average: 3,
    vote_count: 1,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/tTOyhem0IMiDEytNZI3HKyoBZpq.jpg",
    genre_ids: [10767],
    id: 31428,
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Angela and Friends",
    overview:
      "Daily chat show, hosted by Angela Griffin, that combines topical debate with five lifestyle clubs: Diet and Health, Beauty, Books and Travel, Entertainment and Fashion. ",
    popularity: 23.374,
    poster_path: "/j02elNgo62LETB22E3iGmcgyAMI.jpg",
    first_air_date: "2009-11-09",
    name: "Angela and Friends",
    vote_average: 5,
    vote_count: 1,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 229185,
    original_language: "en",
    original_title: "Friends",
    overview:
      "John is a legal assistant who is looking forward to marriage to his fiancee Sally, but his daydream is interrupted when a model plane crashes through his window. Following the plane is a family of six who invade his life and apartment.",
    popularity: 1.097,
    poster_path: "/p0WX0xBopmyjqbCfXVt2dsmLmRM.jpg",
    release_date: "1987-11-20",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/uuzf1bXd3DEBaLgA0XKPMeuGECI.jpg",
    genre_ids: [35, 12, 16],
    id: 644376,
    original_language: "en",
    original_title: "Friends",
    overview:
      "The “small” one is, well, small, and the “big” one is definitely very very big. They are friends.",
    popularity: 0.601,
    poster_path: "/hGKE5aaVo9qBJagEGUERcFAdFzo.jpg",
    release_date: "2019-10-31",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 552783,
    original_language: "en",
    original_title: "Friends",
    overview:
      "A short film about a roller-coaster ride of a friendship between two imaginative young girls.",
    popularity: 0.6,
    poster_path: "/2gxdI27gPPJdpt6qhoqCn8OFAta.jpg",
    release_date: "1972-01-01",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/rYPATzinzCoJPOrjSsJGrIssI8g.jpg",
    genre_ids: [16, 35, 27],
    id: 905020,
    original_language: "en",
    original_title: "Friends",
    overview:
      "Edgar is a lonely crow who just wants to make a friend. Unfortunately for his target, Elena, he goes about it in the worst way possible.",
    popularity: 0.6,
    poster_path: "/nmLoFSlTQnhbSzcsQ9JNCfElGxk.jpg",
    release_date: "2021-08-20",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [27],
    id: 1070057,
    original_language: "fr",
    original_title: "Friends",
    overview: "Short movie written and directed by Sylvain Pelissier.",
    popularity: 0.6,
    poster_path: null,
    release_date: "2018-05-10",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 932483,
    original_language: "xx",
    original_title: "Friends",
    overview:
      "Junko Wada's performance captures the spirit of birds in flight.",
    popularity: 0.6,
    poster_path: "/fucwqXxCADfAYST2xyG1FOaLOqh.jpg",
    release_date: "2011-01-01",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35, 10749],
    id: 926195,
    original_language: "en",
    original_title: "Friends",
    overview: "An overview about the movie Friends",
    popularity: 0.6,
    poster_path: null,
    release_date: "",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 804674,
    original_language: "en",
    original_title: "Friends",
    overview:
      "Scenes from New York in the 1960s. Four young people, friendship, jealousy, separation.",
    popularity: 0.844,
    poster_path: "/tM6EoJ5RJHVjld8s1G8IbvWcETu.jpg",
    release_date: "1967-01-01",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 553665,
    original_language: "en",
    original_title: "Friends",
    overview:
      "A counselor and a student both unhappy with their current lives discuss their future plans",
    popularity: 0.6,
    poster_path: "/gpDoRPACEH2rlbFu494xTYedC2x.jpg",
    release_date: "",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 516437,
    original_language: "en",
    original_title: "Friends",
    overview: "Educational filmstrip about friendship",
    popularity: 0.6,
    poster_path: null,
    release_date: "1972-01-05",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/sZcTPUhwU6U1YLZ13JpDKvJC3EL.jpg",
    genre_ids: [],
    id: 1219598,
    original_language: "fr",
    original_title: "Friends",
    overview: "",
    popularity: 0.6,
    poster_path: "/vPJmtDcswaz6RQaiQdRtQKziSP9.jpg",
    release_date: "",
    title: "Friends",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 36594,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "Friends",
    overview: "",
    popularity: 19.993,
    poster_path: "/4eB6S5yhcIvPu6xydd6uknLG7TH.jpg",
    first_air_date: "2000-07-07",
    name: "Friends",
    vote_average: 0,
    vote_count: 0,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 47550,
    origin_country: [],
    original_language: "ko",
    original_name: "맨발의 친구들",
    overview:
      'Barefooted Friends is a South Korean reality-variety show; a part of SBS\'s Good Sunday lineup, along with Running Man. It was first aired on April 21, 2013. The show is an "real outdoor hardship variety"; a spin on typical outdoor variety shows. The members experience "real happiness" with others through challenges. The words, Barefooted is supposed to mean essence, sincerity, and real hardships, where as Friends not only represents the cast, but the people that are met as well. It has garnered attention as being the come-back program for Kang Ho-dong, the main MC of the program, after leaving Good Sunday\'s X-man in April 2007.',
    popularity: 44.324,
    poster_path: null,
    first_air_date: "2013-04-21",
    name: "Barefooted Friends",
    vote_average: 0,
    vote_count: 0,
    type: "tv",
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 28737,
    origin_country: ["GB", "US"],
    original_language: "en",
    original_name: "My Good Friend",
    overview:
      "My Good Friend was a British television sitcom that ran on ITV between 1995 and 1996. It starred George Cole and Richard Pearson as widowed pensioner Peter Banks and retired librarian Harry King. The show ran for two series, each of seven episodes.",
    popularity: 51.844,
    poster_path: null,
    first_air_date: "1995-04-04",
    name: "Good Friends",
    vote_average: 0,
    vote_count: 0,
    type: "tv",
  },
];
