import { useState, useEffect } from "react";

import {
  AutoScrollCarousel,
  CardsCarousel,
  CardsContainer,
  PeopleCard,
} from "../../components";
import { axiosInstance } from "../../config/axios";
import { movieCastUrl } from "../../utils/queryUrls";
import "./CastCrew.css";

const CastCrew = ({ movieId }) => {
  const [data, setData] = useState([]);

  const fetchData = async () => {
    const res = await axiosInstance({
      method: "get",
      url: `${movieCastUrl}${movieId}/credits`,
    });
    setData((prev) => res.data);
    console.log(res.data);
  };

  useEffect(() => {
    if (movieId) fetchData();
  }, [movieId]);

  return (
    <div className="castcrew-container">
      <AutoScrollCarousel title="top cast">
        {data?.cast?.map((detail) =>
          detail.profile_path ? (
            <PeopleCard key={detail.cast_id} data={detail} />
          ) : null
        )}
      </AutoScrollCarousel>
    </div>
  );
};

export default CastCrew;

// const people = {
//   id: 667538,
//   cast: [
//     {
//       adult: false,
//       gender: 2,
//       id: 1560244,
//       known_for_department: "Acting",
//       name: "Anthony Ramos",
//       original_name: "Anthony Ramos",
//       popularity: 14.962,
//       profile_path: "/2Stnm8PQI7xHkVwINb4MhS7LOuR.jpg",
//       cast_id: 6,
//       character: "Noah Diaz",
//       credit_id: "60662146e1ad790029066453",
//       order: 0,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1676520,
//       known_for_department: "Acting",
//       name: "Dominique Fishback",
//       original_name: "Dominique Fishback",
//       popularity: 6.947,
//       profile_path: "/zduC0PM7xKzFX4F7DH8CCt5gt6O.jpg",
//       cast_id: 7,
//       character: "Elena Wallace",
//       credit_id: "608b0e363852020040ff410d",
//       order: 1,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 19540,
//       known_for_department: "Acting",
//       name: "Peter Cullen",
//       original_name: "Peter Cullen",
//       popularity: 9.887,
//       profile_path: "/9Snf4fBUkk5MrAjqtNtgZRJYJbj.jpg",
//       cast_id: 10,
//       character: "Optimus Prime (voice)",
//       credit_id: "60d25b2b07165000738d3a34",
//       order: 2,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2372,
//       known_for_department: "Acting",
//       name: "Ron Perlman",
//       original_name: "Ron Perlman",
//       popularity: 35.184,
//       profile_path: "/9riPBfsWpzEzh2y9ucxTW22iakI.jpg",
//       cast_id: 11,
//       character: "Optimus Primal (voice)",
//       credit_id: "60d9fd440b731600456062e0",
//       order: 3,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 22970,
//       known_for_department: "Acting",
//       name: "Peter Dinklage",
//       original_name: "Peter Dinklage",
//       popularity: 18.048,
//       profile_path: "/9CAd7wr8QZyIN0E7nm8v1B6WkGn.jpg",
//       cast_id: 59,
//       character: "Scourge (voice)",
//       credit_id: "6388e6840398ab007f8be4f4",
//       order: 4,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1620,
//       known_for_department: "Acting",
//       name: "Michelle Yeoh",
//       original_name: "Michelle Yeoh",
//       popularity: 35.837,
//       profile_path: "/6oxvfyrrM3YmhgFZSqc8ESqPZoC.jpg",
//       cast_id: 40,
//       character: "Airazor (voice)",
//       credit_id: "6345fb88d6c300007f5f9653",
//       order: 5,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1427948,
//       known_for_department: "Acting",
//       name: "Pete Davidson",
//       original_name: "Pete Davidson",
//       popularity: 18.103,
//       profile_path: "/mSlLMk45CUgMGT1o7Pkh9zYaLxK.jpg",
//       cast_id: 41,
//       character: "Mirage (voice)",
//       credit_id: "6345fb9407e2810082f15336",
//       order: 6,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1700631,
//       known_for_department: "Acting",
//       name: "Liza Koshy",
//       original_name: "Liza Koshy",
//       popularity: 5.287,
//       profile_path: "/67PtOsPiLTvyFtRtJ1pK23oJICc.jpg",
//       cast_id: 60,
//       character: "Arcee (voice)",
//       credit_id: "6388e6941b157d00b7888461",
//       order: 7,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2627590,
//       known_for_department: "Acting",
//       name: "Cristo Fernández",
//       original_name: "Cristo Fernández",
//       popularity: 3.805,
//       profile_path: "/pRuCGBvmLgtALcEUcFemzTDYad1.jpg",
//       cast_id: 63,
//       character: "Wheeljack (voice)",
//       credit_id: "6388e790a410c800c887a6a1",
//       order: 8,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 141610,
//       known_for_department: "Acting",
//       name: "Luna Lauren Velez",
//       original_name: "Luna Lauren Velez",
//       popularity: 12.112,
//       profile_path: "/98BvmTJCZHx0jPv0oNcv04Jkmfb.jpg",
//       cast_id: 17,
//       character: "Breanna Diaz",
//       credit_id: "612ee010eb79c200446713ee",
//       order: 9,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2940842,
//       known_for_department: "Acting",
//       name: "Dean Scott Vazquez",
//       original_name: "Dean Scott Vazquez",
//       popularity: 28.224,
//       profile_path: "/bo4Cmv8rXIYSskIbMFbrcIedFnG.jpg",
//       cast_id: 68,
//       character: "Kris Diaz",
//       credit_id: "644b9867336e01054173538e",
//       order: 10,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 3002060,
//       known_for_department: "Acting",
//       name: "Tobe Nwigwe",
//       original_name: "Tobe Nwigwe",
//       popularity: 0.998,
//       profile_path: "/52Zu83S7T9tkzQeQuLyLJgUoXVa.jpg",
//       cast_id: 14,
//       character: "Reek",
//       credit_id: "60ecdb57706e560045c05a3b",
//       order: 11,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1890500,
//       known_for_department: "Acting",
//       name: "Sarah Stiles",
//       original_name: "Sarah Stiles",
//       popularity: 3.245,
//       profile_path: "/t1OuHZmz9GlbFu7bfOUg3nzIki6.jpg",
//       cast_id: 109,
//       character: "Jillian",
//       credit_id: "64826db5e272600107210afc",
//       order: 12,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 90461,
//       known_for_department: "Acting",
//       name: "Leni Parker",
//       original_name: "Leni Parker",
//       popularity: 2.886,
//       profile_path: "/rmOCAuZxYO50EmRxNDdrS3JB6f1.jpg",
//       cast_id: 113,
//       character: "Ms. Greene",
//       credit_id: "64826e6cc9dbf9011dfad449",
//       order: 13,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2069637,
//       known_for_department: "Acting",
//       name: "Frank Marrs",
//       original_name: "Frank Marrs",
//       popularity: 1.008,
//       profile_path: "/6uEP6rv08fuX0vgyEot9FAuY60L.jpg",
//       cast_id: 112,
//       character: "Receptionist",
//       credit_id: "64826e4ec9dbf900e3fe7b3b",
//       order: 14,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 237,
//       known_for_department: "Acting",
//       name: "Aidan Devine",
//       original_name: "Aidan Devine",
//       popularity: 3.858,
//       profile_path: "/3qrUCw73cAN0923x5jCxAiiSaJE.jpg",
//       cast_id: 110,
//       character: "Bishop",
//       credit_id: "64826dcec9dbf900c5708b9b",
//       order: 15,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2567003,
//       known_for_department: "Acting",
//       name: "Kerwin Jackson",
//       original_name: "Kerwin Jackson",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 114,
//       character: "Hotel Security Guard",
//       credit_id: "6486a4fac0348b00aed510b6",
//       order: 16,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 59613,
//       known_for_department: "Crew",
//       name: "Mike Chute",
//       original_name: "Mike Chute",
//       popularity: 5.436,
//       profile_path: "/i1zw8nmh7pWHj3KbrVb2GI5ZY2F.jpg",
//       cast_id: 115,
//       character: "NYC Police Officer",
//       credit_id: "6486a50be272600147baadcd",
//       order: 17,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1890932,
//       known_for_department: "Crew",
//       name: "Tyler Hall",
//       original_name: "Tyler Hall",
//       popularity: 1.202,
//       profile_path: "/lN0FFCcqLTAKMv9uyWYR2o1OPRl.jpg",
//       cast_id: 116,
//       character: "NYC Police Officer",
//       credit_id: "6486a51d028f14013b867899",
//       order: 18,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 937792,
//       known_for_department: "Acting",
//       name: "Sean Tucker",
//       original_name: "Sean Tucker",
//       popularity: 2.274,
//       profile_path: "/45OP1d88I1Gsr57kRv7Q1u3HbW8.jpg",
//       cast_id: 117,
//       character: "Bridge Security Guard",
//       credit_id: "6486a52899259c00ff0f83d6",
//       order: 19,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1199754,
//       known_for_department: "Acting",
//       name: "Jay Farrar",
//       original_name: "Jay Farrar",
//       popularity: 1.4,
//       profile_path: null,
//       cast_id: 118,
//       character: "Museum Guard",
//       credit_id: "6486a539bf31f25054b6b1c4",
//       order: 20,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 4103472,
//       known_for_department: "Acting",
//       name: "Lucas Huarancca",
//       original_name: "Lucas Huarancca",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 111,
//       character: "Amaru",
//       credit_id: "64826e1ce375c000e24e293b",
//       order: 21,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2131852,
//       known_for_department: "Acting",
//       name: "Amiel Cayo",
//       original_name: "Amiel Cayo",
//       popularity: 0.6,
//       profile_path: "/AbkBl3JoWlSbWtpsFqQI7ypTpAe.jpg",
//       cast_id: 119,
//       character: "Amaru's Son",
//       credit_id: "6486a579bf31f250569c5e7f",
//       order: 22,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107906,
//       known_for_department: "Acting",
//       name: "Santusa Cutipa",
//       original_name: "Santusa Cutipa",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 120,
//       character: "Amaru's Wife",
//       credit_id: "6486a58cbf31f2505f3f5eb2",
//       order: 23,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107907,
//       known_for_department: "Acting",
//       name: "Yesenia Inquillay",
//       original_name: "Yesenia Inquillay",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 121,
//       character: "Amaru's Granddaughter",
//       credit_id: "6486a5a2bf31f25055a1c086",
//       order: 24,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107908,
//       known_for_department: "Acting",
//       name: "Sumac T'Ika",
//       original_name: "Sumac T'Ika",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 122,
//       character: "Amaru's Granddaughter",
//       credit_id: "6486a5aee375c000c528aafe",
//       order: 25,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107909,
//       known_for_department: "Acting",
//       name: "Josue Sallo",
//       original_name: "Josue Sallo",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 123,
//       character: "Amaru's Grandson",
//       credit_id: "6486a5bae375c000ff494d5f",
//       order: 26,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107910,
//       known_for_department: "Acting",
//       name: "Mellissa Alvarez",
//       original_name: "Mellissa Alvarez",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 124,
//       character: "Amaru's Daughter-In-Law",
//       credit_id: "6486a5ca99259c00accd948a",
//       order: 27,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4107911,
//       known_for_department: "Acting",
//       name: "Gloria Cusi",
//       original_name: "Gloria Cusi",
//       popularity: 0.6,
//       profile_path: null,
//       cast_id: 125,
//       character: "Amaru's Relative",
//       credit_id: "6486a5d2e375c00139c1041e",
//       order: 28,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 50217,
//       known_for_department: "Acting",
//       name: "Michael Kelly",
//       original_name: "Michael Kelly",
//       popularity: 14.82,
//       profile_path: "/8V6RKWbbx8lyt3Xxz9B1OAPvHRt.jpg",
//       cast_id: 71,
//       character: "Agent Burke",
//       credit_id: "6472c80195665800a8d821c5",
//       order: 29,
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1070318,
//       known_for_department: "Acting",
//       name: "Jason D. Avalos",
//       original_name: "Jason D. Avalos",
//       popularity: 0.762,
//       profile_path: null,
//       cast_id: 126,
//       character: "Security Guard",
//       credit_id: "6486a5eae375c00139c1043d",
//       order: 30,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 197819,
//       known_for_department: "Acting",
//       name: "Lesley Stahl",
//       original_name: "Lesley Stahl",
//       popularity: 1.95,
//       profile_path: "/m0vTn5aGk0bw3BNm29wpJHvPpAA.jpg",
//       cast_id: 127,
//       character: "Lesley Stahl",
//       credit_id: "6486a600e375c000ff494d87",
//       order: 31,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 31531,
//       known_for_department: "Acting",
//       name: "John DiMaggio",
//       original_name: "John DiMaggio",
//       popularity: 11.864,
//       profile_path: "/awmyFwU6ErFJbGFFzhBYZ9AQn8m.jpg",
//       cast_id: 61,
//       character: "Transit / Stratosphere (voice)",
//       credit_id: "6388e7530398ab007c887aff",
//       order: 32,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 164614,
//       known_for_department: "Acting",
//       name: "David Sobolov",
//       original_name: "David Sobolov",
//       popularity: 5.897,
//       profile_path: "/eOBHvvlfQQ4b4120YJ2c2C7anKR.jpg",
//       cast_id: 62,
//       character: "Rhinox / Battletrap / Apelinq (voice)",
//       credit_id: "6388e7800398ab007c887b08",
//       order: 33,
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1518933,
//       known_for_department: "Acting",
//       name: "Michaela Jaé Rodriguez",
//       original_name: "Michaela Jaé Rodriguez",
//       popularity: 5.317,
//       profile_path: "/ow7NJkG2ClrHdg13cN8uVvXmESf.jpg",
//       cast_id: 64,
//       character: "Nightbird (voice)",
//       credit_id: "6388e7b3229ae2158118b5e8",
//       order: 34,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 91671,
//       known_for_department: "Acting",
//       name: "Colman Domingo",
//       original_name: "Colman Domingo",
//       popularity: 7.57,
//       profile_path: "/2tu6T9ugnf82qIMGVKWSb0dvvq5.jpg",
//       cast_id: 69,
//       character: "Unicron (voice)",
//       credit_id: "644c7ff4596a91054d583299",
//       order: 35,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 105875,
//       known_for_department: "Acting",
//       name: "Tongayi Chirisa",
//       original_name: "Tongayi Chirisa",
//       popularity: 5.488,
//       profile_path: "/iNUnPz0fcz2kGYZ5lhkXo042iAl.jpg",
//       cast_id: 67,
//       character: "Cheetor (voice)",
//       credit_id: "644b9829726fb1054a06107d",
//       order: 36,
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1517706,
//       known_for_department: "Acting",
//       name: "Luke Jones",
//       original_name: "Luke Jones",
//       popularity: 2.46,
//       profile_path: "/cwwKbw74j5W2MQse64keCl7eGIi.jpg",
//       cast_id: 128,
//       character: "Additional Voice (voice)",
//       credit_id: "6486a766028f1400e4b22021",
//       order: 37,
//     },
//   ],
//   crew: [
//     {
//       adult: false,
//       gender: 2,
//       id: 488,
//       known_for_department: "Directing",
//       name: "Steven Spielberg",
//       original_name: "Steven Spielberg",
//       popularity: 26.915,
//       profile_path: "/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg",
//       credit_id: "6154561967dcc90043e3757a",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 15841,
//       known_for_department: "Editing",
//       name: "William Goldenberg",
//       original_name: "William Goldenberg",
//       popularity: 5.496,
//       profile_path: "/eOgoea8HbZt2TfLn0tDNI1TepSN.jpg",
//       credit_id: "647ea96eccde0400de90496b",
//       department: "Editing",
//       job: "Editor",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 865,
//       known_for_department: "Production",
//       name: "Michael Bay",
//       original_name: "Michael Bay",
//       popularity: 18.657,
//       profile_path: "/8I9H9IKROECFEn7usvyChbRMhbI.jpg",
//       credit_id: "6346230c699fb70081dc5b31",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 3183,
//       known_for_department: "Production",
//       name: "Don Murphy",
//       original_name: "Don Murphy",
//       popularity: 1.602,
//       profile_path: "/xX9mLKLbsnYhdRMrdpK2ULJIe0s.jpg",
//       credit_id: "6388e9fb1b157d009718bc43",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 3964,
//       known_for_department: "Art",
//       name: "Patrick Tatopoulos",
//       original_name: "Patrick Tatopoulos",
//       popularity: 1.552,
//       profile_path: "/6tkcPHANqVx7sXTXKR8knw87h06.jpg",
//       credit_id: "615456ade8a3e10043033ca6",
//       department: "Art",
//       job: "Production Design",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 6870,
//       known_for_department: "Production",
//       name: "Duncan Henderson",
//       original_name: "Duncan Henderson",
//       popularity: 1.967,
//       profile_path: null,
//       credit_id: "634622eb07e2810082f16f35",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 10952,
//       known_for_department: "Production",
//       name: "Lorenzo di Bonaventura",
//       original_name: "Lorenzo di Bonaventura",
//       popularity: 1.355,
//       profile_path: "/skMUk4eVV6e08mv31A48jdYpEPp.jpg",
//       credit_id: "5fb33b71ec4552003efa9198",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 9271,
//       known_for_department: "Art",
//       name: "Michele Laliberte",
//       original_name: "Michele Laliberte",
//       popularity: 0.796,
//       profile_path: null,
//       credit_id: "647ea9ebcf4b8b01419092b4",
//       department: "Art",
//       job: "Supervising Art Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 9776,
//       known_for_department: "Production",
//       name: "Chantal Feghali",
//       original_name: "Chantal Feghali",
//       popularity: 2.201,
//       profile_path: null,
//       credit_id: "6154580fe8a3e10043033e91",
//       department: "Visual Effects",
//       job: "Visual Effects Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 13245,
//       known_for_department: "Editing",
//       name: "Joel Negron",
//       original_name: "Joel Negron",
//       popularity: 0.928,
//       profile_path: null,
//       credit_id: "647ea977caef2d00df8a04e9",
//       department: "Editing",
//       job: "Editor",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 17598,
//       known_for_department: "Camera",
//       name: "Enrique Chediak",
//       original_name: "Enrique Chediak",
//       popularity: 1.226,
//       profile_path: null,
//       credit_id: "612edf01fac5020026fce2e2",
//       department: "Camera",
//       job: "Director of Photography",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 10994,
//       known_for_department: "Production",
//       name: "Tom DeSanto",
//       original_name: "Tom DeSanto",
//       popularity: 4.872,
//       profile_path: null,
//       credit_id: "6388e9f1d388ae007f5821ff",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 24308,
//       known_for_department: "Production",
//       name: "Brian Goldner",
//       original_name: "Brian Goldner",
//       popularity: 0.931,
//       profile_path: null,
//       credit_id: "61545674e18b97008c9759e4",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 24309,
//       known_for_department: "Production",
//       name: "Mark Vahradian",
//       original_name: "Mark Vahradian",
//       popularity: 2.94,
//       profile_path: "/soKYRPi4hYTnVABGkAGCRGnU87J.jpg",
//       credit_id: "6154560ddd731b0042a5fcca",
//       department: "Production",
//       job: "Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 20208,
//       known_for_department: "Production",
//       name: "Brad Fischer",
//       original_name: "Brad Fischer",
//       popularity: 1.768,
//       profile_path: "/xJbGB0pDWKc4tniAQpFxhL7xLyT.jpg",
//       credit_id: "6154568afe6c18008b4680a2",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 20227,
//       known_for_department: "Sound",
//       name: "Felix Andrew",
//       original_name: "Felix Andrew",
//       popularity: 0.979,
//       profile_path: null,
//       credit_id: "647eaba893828e00a765dea2",
//       department: "Sound",
//       job: "Sound Mixer",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 29018,
//       known_for_department: "Production",
//       name: "Dana Goldberg",
//       original_name: "Dana Goldberg",
//       popularity: 2.745,
//       profile_path: null,
//       credit_id: "6154567ffe6c180062a9705a",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 56737,
//       known_for_department: "Production",
//       name: "Don Granger",
//       original_name: "Don Granger",
//       popularity: 2.25,
//       profile_path: "/ilhrUzybaDqaZOiaw1M8dzkZ0ZF.jpg",
//       credit_id: "61545668fe6c1800428e0a94",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 57049,
//       known_for_department: "Production",
//       name: "Brian Oliver",
//       original_name: "Brian Oliver",
//       popularity: 0.926,
//       profile_path: "/jjRoepjAT6nDzNEglANnM9ppPxa.jpg",
//       credit_id: "6154564ddd731b008b8bf77b",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 58433,
//       known_for_department: "Production",
//       name: "David Ellison",
//       original_name: "David Ellison",
//       popularity: 3.597,
//       profile_path: "/jOhjFZWW2KqsOzm4IiE71FHmcIf.jpg",
//       credit_id: "6154569743d9b100294b088f",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 74569,
//       known_for_department: "Writing",
//       name: "Joby Harold",
//       original_name: "Joby Harold",
//       popularity: 2.237,
//       profile_path: "/q3jMKt9f93fZwJHVQoov0hFAFwJ.jpg",
//       credit_id: "5e2f8fdcac8e6b0015bd5c86",
//       department: "Writing",
//       job: "Screenplay",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 74569,
//       known_for_department: "Writing",
//       name: "Joby Harold",
//       original_name: "Joby Harold",
//       popularity: 2.237,
//       profile_path: "/q3jMKt9f93fZwJHVQoov0hFAFwJ.jpg",
//       credit_id: "634623bfcf62cd007eae2392",
//       department: "Writing",
//       job: "Story",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 112947,
//       known_for_department: "Writing",
//       name: "Erich Hoeber",
//       original_name: "Erich Hoeber",
//       popularity: 2.262,
//       profile_path: "/iIV4kJKeaOth7n7iYVMOl2DQ3lw.jpg",
//       credit_id: "634623a7f3b49a007c955918",
//       department: "Writing",
//       job: "Screenplay",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 112948,
//       known_for_department: "Writing",
//       name: "Jon Hoeber",
//       original_name: "Jon Hoeber",
//       popularity: 2.708,
//       profile_path: null,
//       credit_id: "634623acd55c3d007a1acb8a",
//       department: "Writing",
//       job: "Screenplay",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1097215,
//       known_for_department: "Crew",
//       name: "Vaia Zaganas",
//       original_name: "Vaia Zaganas",
//       popularity: 1.174,
//       profile_path: "/hrILpV8bSEe1BYPNkN4mRai8mJW.jpg",
//       credit_id: "636df3a981383100dd361001",
//       department: "Crew",
//       job: "Stunts",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1193446,
//       known_for_department: "Art",
//       name: "Anthony Leonardi III",
//       original_name: "Anthony Leonardi III",
//       popularity: 0.818,
//       profile_path: null,
//       credit_id: "647eaab393828e0133791e3f",
//       department: "Directing",
//       job: "Second Unit Director",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1269034,
//       known_for_department: "Crew",
//       name: "Jen Weissenberg",
//       original_name: "Jen Weissenberg",
//       popularity: 1.81,
//       profile_path: "/eldqpfXTxspQmIr7LQ2qqnWwPYs.jpg",
//       credit_id: "636df3c8d7fbda00e7b750be",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1326399,
//       known_for_department: "Art",
//       name: "Louis Dandonneau",
//       original_name: "Louis Dandonneau",
//       popularity: 0.668,
//       profile_path: null,
//       credit_id: "647eaa19ccde0400c13aad03",
//       department: "Art",
//       job: "Set Decoration",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1327222,
//       known_for_department: "Art",
//       name: "Philippe Lord",
//       original_name: "Philippe Lord",
//       popularity: 1.4,
//       profile_path: null,
//       credit_id: "6154571ed1ca2a0042646d04",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1378695,
//       known_for_department: "Sound",
//       name: "Erik Aadahl",
//       original_name: "Erik Aadahl",
//       popularity: 1.4,
//       profile_path: "/Ny1Ru6rlJFGmIB1vhbP9ENZsqo.jpg",
//       credit_id: "647eab9a0fb39800fb0d017b",
//       department: "Sound",
//       job: "Sound Designer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1378695,
//       known_for_department: "Sound",
//       name: "Erik Aadahl",
//       original_name: "Erik Aadahl",
//       popularity: 1.4,
//       profile_path: "/Ny1Ru6rlJFGmIB1vhbP9ENZsqo.jpg",
//       credit_id: "647eab94ccde0400fbcee21b",
//       department: "Sound",
//       job: "Supervising Sound Editor",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1384359,
//       known_for_department: "Art",
//       name: "Félix Larivière-Charron",
//       original_name: "Félix Larivière-Charron",
//       popularity: 1.208,
//       profile_path: null,
//       credit_id: "647ea9fdcf4b8b01419092be",
//       department: "Art",
//       job: "Supervising Art Director",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1384360,
//       known_for_department: "Art",
//       name: "Ann Smart",
//       original_name: "Ann Smart",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "6154572add731b006201d390",
//       department: "Art",
//       job: "Set Decoration",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1398122,
//       known_for_department: "Acting",
//       name: "Gui DaSilva-Greene",
//       original_name: "Gui DaSilva-Greene",
//       popularity: 1.637,
//       profile_path: "/8scb1cYtbaGsrlVJ7szgIBjiuXE.jpg",
//       credit_id: "64cfb6d4d9f4a603bafac9bb",
//       department: "Crew",
//       job: "Stunts",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1402019,
//       known_for_department: "Costume & Make-Up",
//       name: "Colleen Quinton",
//       original_name: "Colleen Quinton",
//       popularity: 0.84,
//       profile_path: null,
//       credit_id: "6154574643d9b10043997e54",
//       department: "Costume & Make-Up",
//       job: "Makeup Designer",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1425353,
//       known_for_department: "Art",
//       name: "Mathieu Giguère",
//       original_name: "Mathieu Giguère",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "6154570de18b9700628ef275",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1445475,
//       known_for_department: "Art",
//       name: "Arthur Jongewaard",
//       original_name: "Arthur Jongewaard",
//       popularity: 1.0,
//       profile_path: null,
//       credit_id: "647ea9e193828e011625f13f",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1510496,
//       known_for_department: "Acting",
//       name: "Rodney Alexandre",
//       original_name: "Rodney Alexandre",
//       popularity: 1.645,
//       profile_path: "/2yWvyUvq4dNEamZPjpTCWNYR9jo.jpg",
//       credit_id: "636df34021621b00b49e1e8d",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1538204,
//       known_for_department: "Production",
//       name: "Wittney Horton",
//       original_name: "Wittney Horton",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9810fb39800a7a0106d",
//       department: "Production",
//       job: "Casting",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1551545,
//       known_for_department: "Directing",
//       name: "Steven Caple Jr.",
//       original_name: "Steven Caple Jr.",
//       popularity: 2.757,
//       profile_path: "/aU8p958QyhfV2jurc3L5pn7sN6L.jpg",
//       credit_id: "5fb33ac6d55e4d003cd58727",
//       department: "Directing",
//       job: "Director",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1631516,
//       known_for_department: "Production",
//       name: "Cliff Lanning",
//       original_name: "Cliff Lanning",
//       popularity: 2.262,
//       profile_path: "/fMbBthNyuTtB2bayJHSrmrWIR0G.jpg",
//       credit_id: "647eaaa80fb39800de68a44b",
//       department: "Directing",
//       job: "First Assistant Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1635225,
//       known_for_department: "Crew",
//       name: "Alvin Zalamea",
//       original_name: "Alvin Zalamea",
//       popularity: 1.164,
//       profile_path: null,
//       credit_id: "636df392d7fbda00bb8f8259",
//       department: "Crew",
//       job: "Stunt Double",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1640991,
//       known_for_department: "Art",
//       name: "Brent David Mannon",
//       original_name: "Brent David Mannon",
//       popularity: 1.38,
//       profile_path: null,
//       credit_id: "647eaa22ccde0401355c3995",
//       department: "Art",
//       job: "Set Decoration",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1663700,
//       known_for_department: "Sound",
//       name: "Jongnic Bontemps",
//       original_name: "Jongnic Bontemps",
//       popularity: 0.884,
//       profile_path: null,
//       credit_id: "646d29ae9661fc0157366504",
//       department: "Sound",
//       job: "Original Music Composer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1731667,
//       known_for_department: "Costume & Make-Up",
//       name: "Ciara Whaley",
//       original_name: "Ciara Whaley",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "61545735af58cb0044e29991",
//       department: "Costume & Make-Up",
//       job: "Costume Design",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 1810161,
//       known_for_department: "Art",
//       name: "Marie-Soleil Dénommé",
//       original_name: "Marie-Soleil Dénommé",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9d6caef2d00df8a0514",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1867396,
//       known_for_department: "Art",
//       name: "Georges Samuel",
//       original_name: "Georges Samuel",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab3b93828e00f9d8d398",
//       department: "Art",
//       job: "Set Dresser",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1890965,
//       known_for_department: "Art",
//       name: "Frédéric Berthiaume",
//       original_name: "Frédéric Berthiaume",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9a30e29a22be293a8e6",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1929030,
//       known_for_department: "Art",
//       name: "Radia Slaimi",
//       original_name: "Radia Slaimi",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab7bcaef2d00fce6ffb2",
//       department: "Art",
//       job: "Set Designer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 1938584,
//       known_for_department: "Crew",
//       name: "Nathalie Legault",
//       original_name: "Nathalie Legault",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea93e0e29a22be3284621",
//       department: "Costume & Make-Up",
//       job: "Makeup Artist",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 1981111,
//       known_for_department: "Art",
//       name: "Dennis Ogle",
//       original_name: "Dennis Ogle",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab2c0fb39801355a903d",
//       department: "Art",
//       job: "Set Decoration Buyer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2121799,
//       known_for_department: "Art",
//       name: "Manuel Charbonneau",
//       original_name: "Manuel Charbonneau",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaaf993828e0133791e5a",
//       department: "Art",
//       job: "Set Dresser",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 2224819,
//       known_for_department: "Crew",
//       name: "Nitasha Bhambree",
//       original_name: "Nitasha Bhambree",
//       popularity: 0.682,
//       profile_path: null,
//       credit_id: "636df3511684f700c4ea414a",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2252524,
//       known_for_department: "Directing",
//       name: "Geneviéve Duguay",
//       original_name: "Geneviéve Duguay",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaa720fb39800de68a42d",
//       department: "Directing",
//       job: "Third Assistant Director",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2295472,
//       known_for_department: "Crew",
//       name: "Adam Winlove-Smith",
//       original_name: "Adam Winlove-Smith",
//       popularity: 0.6,
//       profile_path: "/5zdDvfKOBiCP0i4kurhz4wvfgym.jpg",
//       credit_id: "636df3b61684f70083dbcf63",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 2300589,
//       known_for_department: "Crew",
//       name: "Stephannie Hawkins",
//       original_name: "Stephannie Hawkins",
//       popularity: 9.934,
//       profile_path: "/tXsJfDknfeB4lt1LbVw0hAqxHHb.jpg",
//       credit_id: "636df311d7fbda00ca8ba8df",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 2300590,
//       known_for_department: "Crew",
//       name: "E. Nova Zatzman",
//       original_name: "E. Nova Zatzman",
//       popularity: 1.041,
//       profile_path: "/4wNYheN7WXrp1nR4ugwr5vwZwt3.jpg",
//       credit_id: "636df36d1684f700ab805ddf",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 2389963,
//       known_for_department: "Art",
//       name: "Simon Théberge",
//       original_name: "Simon Théberge",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab850e29a22be08e643f",
//       department: "Art",
//       job: "Set Designer",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 2431754,
//       known_for_department: "Art",
//       name: "Ève Boulonne",
//       original_name: "Ève Boulonne",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9bbccde0400c13aacd5",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2435602,
//       known_for_department: "Art",
//       name: "Travis Nunnally",
//       original_name: "Travis Nunnally",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab210e29a22bdfece642",
//       department: "Art",
//       job: "Set Dresser",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 2560300,
//       known_for_department: "Crew",
//       name: "Vanessa Zamarripa",
//       original_name: "Vanessa Zamarripa",
//       popularity: 2.538,
//       profile_path: "/wxGSsJ53bQPVOG3JRjlCSVrxHPs.jpg",
//       credit_id: "636df37cd7fbda0088757c04",
//       department: "Crew",
//       job: "Stunts",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2561259,
//       known_for_department: "Costume & Make-Up",
//       name: "Eli Girard",
//       original_name: "Eli Girard",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea933caef2d00df8a04c6",
//       department: "Costume & Make-Up",
//       job: "Hairstylist",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2615718,
//       known_for_department: "Art",
//       name: "Michael Nallan",
//       original_name: "Michael Nallan",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaa2dcf4b8b00a878f11c",
//       department: "Art",
//       job: "Set Decoration",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2806442,
//       known_for_department: "Art",
//       name: "Shoko Kambara",
//       original_name: "Shoko Kambara",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab100e29a22bdfece636",
//       department: "Art",
//       job: "Assistant Art Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 2998872,
//       known_for_department: "Production",
//       name: "Valerii An",
//       original_name: "Valerii An",
//       popularity: 1.4,
//       profile_path: null,
//       credit_id: "615455eae8a3e10062205c5a",
//       department: "Production",
//       job: "Executive Producer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3005590,
//       known_for_department: "Art",
//       name: "Eduardo Santibanez",
//       original_name: "Eduardo Santibanez",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eab47ccde0400de904a35",
//       department: "Art",
//       job: "Set Dresser",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3072850,
//       known_for_department: "Writing",
//       name: "Darnell Metayer",
//       original_name: "Darnell Metayer",
//       popularity: 0.711,
//       profile_path: null,
//       credit_id: "63462393cdf2e6007ad2a2c0",
//       department: "Writing",
//       job: "Screenplay",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3072852,
//       known_for_department: "Writing",
//       name: "Josh Peters",
//       original_name: "Josh Peters",
//       popularity: 0.98,
//       profile_path: null,
//       credit_id: "634623a0f621b20079f98b95",
//       department: "Writing",
//       job: "Screenplay",
//     },
//     {
//       adult: false,
//       gender: 2,
//       id: 3128690,
//       known_for_department: "Costume & Make-Up",
//       name: "Frédéric Bélanger",
//       original_name: "Frédéric Bélanger",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea905ccde0400c13aac83",
//       department: "Costume & Make-Up",
//       job: "Hair Department Head",
//     },
//     {
//       adult: false,
//       gender: 1,
//       id: 3158816,
//       known_for_department: "Art",
//       name: "Caroline Davignon",
//       original_name: "Caroline Davignon",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9c6caef2d00fce6ff02",
//       department: "Art",
//       job: "Art Direction",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3231077,
//       known_for_department: "Art",
//       name: "Clothilde Caillé-Levesque",
//       original_name: "Clothilde Caillé-Levesque",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaaefccde040118aae629",
//       department: "Art",
//       job: "Set Designer",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3527987,
//       known_for_department: "Crew",
//       name: "Kye Walstrom",
//       original_name: "Kye Walstrom",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "636df3d721621b007dd9348c",
//       department: "Crew",
//       job: "Stunt Driver",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3743667,
//       known_for_department: "Directing",
//       name: "Esteban Sánchez",
//       original_name: "Esteban Sánchez",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaadccf4b8b00c3d3996f",
//       department: "Directing",
//       job: "Second Assistant Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 3987675,
//       known_for_department: "Directing",
//       name: "James Madigan",
//       original_name: "James Madigan",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaac6caef2d00c29bb41b",
//       department: "Directing",
//       job: "Second Unit Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4099165,
//       known_for_department: "Costume & Make-Up",
//       name: "Melissa Puch",
//       original_name: "Melissa Puch",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea94993828e00dcde3a42",
//       department: "Costume & Make-Up",
//       job: "Makeup Artist",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4099166,
//       known_for_department: "Costume & Make-Up",
//       name: "Soraya Qadi",
//       original_name: "Soraya Qadi",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647ea9550e29a22be1f0ec91",
//       department: "Costume & Make-Up",
//       job: "Key Hair Stylist",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4099171,
//       known_for_department: "Directing",
//       name: "Clara Haddad",
//       original_name: "Clara Haddad",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaa9793828e00a765de39",
//       department: "Directing",
//       job: "Third Assistant Director",
//     },
//     {
//       adult: false,
//       gender: 0,
//       id: 4099175,
//       known_for_department: "Art",
//       name: "Dale Byrns",
//       original_name: "Dale Byrns",
//       popularity: 0.6,
//       profile_path: null,
//       credit_id: "647eaae7caef2d01362c99b2",
//       department: "Art",
//       job: "Set Designer",
//     },
//   ],
// };
