import { useParams } from "react-router-dom";
import { apiEndPoints } from "../../statics/constants";
import "./MovieDetail.css";
import { useEffect } from "react";
import { useState } from "react";
import { fetchOptions } from "../../utils/helpers";
import { useGetMovieDetail } from "../../hooks/useGetMovieDetail";
import MovieDetail from "./MovieDetail";

const MovieDetailPage = () => {
  const { movieId } = useParams();

  const [movieDetail] = useGetMovieDetail({ movieId });

  return (
    <div className="movieDetailPage-container">
      <MovieDetail {...movieDetail} />
    </div>
  );
};

export default MovieDetailPage;

const movie = {
  id: 609681,
  title: "The Marvels",
  genres: [
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 28,
      name: "Action",
    },
  ],
  runtime: 105,
  tagline: "Higher. Further. Faster. Together.",
  overview:
    "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
  rating: 6.372,
  moviePoster: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
  backdropPath: "/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg",
  trailerLink: "uwmDH12MAA4",
  socialIds: {
    imdb_id: "tt10676048",
    wikidata_id: "Q89474225",
    facebook_id: "CaptainMarvelOfficial",
    instagram_id: "captainmarvelofficial",
    twitter_id: "captainmarvel",
  },
  homepage: "https://www.marvel.com/movies/the-marvels",
  language: "English",
  budget: 274800000,
  revenue: 205600000,
  cast: {
    totalCount: 33,
    data: [
      {
        adult: false,
        gender: 1,
        id: 60073,
        known_for_department: "Acting",
        name: "Brie Larson",
        original_name: "Brie Larson",
        popularity: 54.817,
        profile_path: "/nbh2NPwPTKl2Y08CYKe1OXRA0bO.jpg",
        cast_id: 1,
        character: "Carol Danvers / Captain Marvel",
        credit_id: "5d08fd3bc3a3687c751ef54c",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 970219,
        known_for_department: "Acting",
        name: "Teyonah Parris",
        original_name: "Teyonah Parris",
        popularity: 33.436,
        profile_path: "/mArqi5mGbKvfrNsrEEkdy0gDvGu.jpg",
        cast_id: 15,
        character: "Monica Rambeau",
        credit_id: "5fd2c387fea0d7003c840847",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 2798462,
        known_for_department: "Acting",
        name: "Iman Vellani",
        original_name: "Iman Vellani",
        popularity: 21.096,
        profile_path: "/tAq0b5qS1NyAMUtsSkm68BRYahm.jpg",
        cast_id: 14,
        character: "Kamala Khan / Ms. Marvel",
        credit_id: "5fd2c34c1d3143003c47b952",
        order: 2,
      },
      {
        adult: false,
        gender: 1,
        id: 118034,
        known_for_department: "Acting",
        name: "Zawe Ashton",
        original_name: "Zawe Ashton",
        popularity: 20.117,
        profile_path: "/zbxVfvhPhCfgpgmWTdtHWurNqYu.jpg",
        cast_id: 17,
        character: "Dar-Benn",
        credit_id: "6026ba144a4bfc0040a6ef29",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 2231,
        known_for_department: "Acting",
        name: "Samuel L. Jackson",
        original_name: "Samuel L. Jackson",
        popularity: 71.234,
        profile_path: "/nCJJ3NVksYNxIzEHcyC1XziwPVj.jpg",
        cast_id: 29,
        character: "Nick Fury",
        credit_id: "61157fa387f3f2002c279d02",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 480,
        known_for_department: "Acting",
        name: "Gary Lewis",
        original_name: "Gary Lewis",
        popularity: 23.175,
        profile_path: "/cOaibfAluUeWPtcSOjedfGXn9ym.jpg",
        cast_id: 60,
        character: "Emperor Dro'ge",
        credit_id: "64b8bd5f1685da00acaf0916",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 1347525,
        known_for_department: "Acting",
        name: "Park Seo-jun",
        original_name: "Park Seo-jun",
        popularity: 52.054,
        profile_path: "/rLAhC54IdUBRmpSRQrCC6a0wTLV.jpg",
        cast_id: 28,
        character: "Prince Yan",
        credit_id: "6100efaccee481002dd72c53",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 1809782,
        known_for_department: "Acting",
        name: "Zenobia Shroff",
        original_name: "Zenobia Shroff",
        popularity: 22.23,
        profile_path: "/zo3GlNoJkjtKMbZc5hcwmE5q9C6.jpg",
        cast_id: 33,
        character: "Muneeba Khan",
        credit_id: "614433e29f0e19004373178c",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 1014905,
        known_for_department: "Acting",
        name: "Mohan Kapur",
        original_name: "Mohan Kapur",
        popularity: 22.471,
        profile_path: "/lL0J5DBOwN1pwLCvuo7uQ0ApjF.jpg",
        cast_id: 32,
        character: "Yusuf Khan",
        credit_id: "614433cb56b9f700288901c2",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 2889306,
        known_for_department: "Acting",
        name: "Saagar Shaikh",
        original_name: "Saagar Shaikh",
        popularity: 6.448,
        profile_path: "/dipfu3fGTNcLPvmRuh9I7HWRzhr.jpg",
        cast_id: 34,
        character: "Aamir Khan",
        credit_id: "614433f885da12008ca1e753",
        order: 9,
      },
      {
        adult: false,
        gender: 1,
        id: 2044882,
        known_for_department: "Acting",
        name: "Leila Farzad",
        original_name: "Leila Farzad",
        popularity: 3.368,
        profile_path: "/cjB87g9aZOfmgKBvYhfNCJUM1Kn.jpg",
        cast_id: 149,
        character: "Talia",
        credit_id: "654c9b9867b61300afc95e04",
        order: 10,
      },
      {
        adult: false,
        gender: 2,
        id: 1432064,
        known_for_department: "Acting",
        name: "Abraham Popoola",
        original_name: "Abraham Popoola",
        popularity: 19.778,
        profile_path: "/r5mojn6TjWgHefdMCJNiohvY82f.jpg",
        cast_id: 150,
        character: "Dag",
        credit_id: "654c9ba529383501387d4580",
        order: 11,
      },
      {
        adult: false,
        gender: 1,
        id: 1360281,
        known_for_department: "Acting",
        name: "Lashana Lynch",
        original_name: "Lashana Lynch",
        popularity: 34.488,
        profile_path: "/ypNxRag9uJ5nzPAN2um3amQK340.jpg",
        cast_id: 148,
        character: "Maria Rambeau",
        credit_id: "654c9b8bb18f3200e2cf8b53",
        order: 12,
      },
      {
        adult: false,
        gender: 1,
        id: 62561,
        known_for_department: "Acting",
        name: "Tessa Thompson",
        original_name: "Tessa Thompson",
        popularity: 19.918,
        profile_path: "/cJ64yI9OiQN8Edp4FgAHiLuoWiQ.jpg",
        cast_id: 165,
        character: "Valkyrie",
        credit_id: "654c9cd45a5ed001003fe567",
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 1131724,
        known_for_department: "Acting",
        name: "Daniel Ings",
        original_name: "Daniel Ings",
        popularity: 28.064,
        profile_path: "/VHtgRMz5t0F8DEjYMxSmY09DTw.jpg",
        cast_id: 151,
        character: "Ty-Rone",
        credit_id: "654c9bb22866fa108e073fc0",
        order: 14,
      },
    ],
  },
  isEasterMovie: false,
  reviews: [
    {
      author: "Manuel São Bento",
      author_details: {
        name: "Manuel São Bento",
        username: "msbreviews",
        avatar_path: null,
        rating: 7,
      },
      content:
        'FULL SPOILER-FREE REVIEW @ https://www.firstshowing.net/2023/review-nia-dacostas-the-marvels-is-a-solid-mid-tier-mcu-movie/\r\n\r\n"The Marvels is a film that showcases some of the well-known strengths and weaknesses of the MCU. It struggles with script and editing issues that hinder its narrative cohesion and character depth, besides an unnecessarily short runtime that doesn’t help its villain.\r\n\r\nFortunately, it excels in its ensemble cast and their chemistry - Iman Vellani is the clear MVP - creative action set pieces, impressive visual effects, stunning costumes, and well-timed humor, which all together push the movie into safe harbor.\r\n\r\nNia DaCosta offers a light, entertaining superhero blockbuster that may fall short of greatness, but leaves room for improvement in future installments of the franchise."\r\n\r\nRating: B',
      created_at: "2023-11-09T19:42:31.799Z",
      id: "654d36275a5ed000c6ad204a",
      updated_at: "2023-11-09T19:42:31.931Z",
      url: "https://www.themoviedb.org/review/654d36275a5ed000c6ad204a",
    },
    {
      author: "CinemaSerf",
      author_details: {
        name: "CinemaSerf",
        username: "Geronimo1967",
        avatar_path: "/1kks3YnVkpyQxzw36CObFPvhL5f.jpg",
        rating: 6,
      },
      content:
        'When Kree ruler "Dar-Benn" (Zawe Ashton) unearths a powerful bracelet, she unleashes a power in it\'s sister being worn, decoratively, by the enthusiastic but a bit annoying "Kamala" (Iman Vellani) and next thing we find chaos ensues. It appears that her new powers connect her to "Danvers" (Brie Larson) and her slightly estranged cohort "Rambeau" (Teyonah Parris). When they use their powers they find themselves transported into each other\'s shoes - causing mayhem all over the place, especially at the family home of the rookie superhero who is as yet unaware of just quite how powerful her shiny amulet is. "Dar-Benn" is out for revenge. After "Danvers" destroyed the AI that controlled their planet, it has gone into terminal decay and so she decides to reinstate her world by stealing the atmosphere from one world, then the water from another - where they only speak in song, so perhaps no great loss - before deciding to borrow the sun from Earth to reinvigorate their own failing star. With a little help from "Nick Fury" (Samuel L. Jackson) the three have to galvanise their powers and focus on thwarting this dastardly design before it\'s too late. Now there is nothing even remotely original in this. It\'s all join the dots Marvel adventure with the usual pyrotechnics, spectacular visual effects and thinnest of stories. The denouement is never in doubt and actually feels rather rushed after a first half hour of repetitive combat scenes that don\'t draw breath but don\'t really entertain either. Larson is a natural actor (she reminds me a lot of Grace Kelly) but nobody here really has much by way of dialogue to work with as we see this film manoeuvred into the path of another franchise that it would appear destined to join with next time. Barbra Streisand makes a surprise (vocal) appearance during quite an innovative scene herding cats and simultaneously saving people, but I found the rest of this to be same old, same old and though shorter than we are used to, it\'s still all a bit old hat. Looks good, but I doubt that you\'ll never remember it.',
      created_at: "2023-11-11T09:46:05.135Z",
      id: "654f4d5d67b6130102e3625f",
      updated_at: "2023-11-11T09:48:34.603Z",
      url: "https://www.themoviedb.org/review/654f4d5d67b6130102e3625f",
    },
    {
      author: "Brent Marchant",
      author_details: {
        name: "Brent Marchant",
        username: "Brent_Marchant",
        avatar_path: null,
        rating: 5,
      },
      content:
        "When I first heard the title of this movie, I thought it was about a 1960s girls’ singing group. And, frankly, that would have probably made for a better movie. Writer-director Nia DaCosta’s third feature outing and the latest in the Marvel Universe paradigm is a wildly inconsistent superhero movie that tries too hard to do too much and doesn’t have a script to support it. Too many of its plot elements aren’t adequately explained until well into the story, while others aren’t explained at all, leaving viewers who aren’t comic book laureates wondering what’s going on (particularly at film’s end). Meanwhile, other narrative aspects frequently appear gimmicky and grow old quickly, such as the introduction of the primary superpower that its three protagonists share, one that almost becomes slapstickish after an all-too-brief while. On top of that, the CGI effects vacillate from one end of the quality spectrum to the other, creating a mix of images that are either startling to look at or stunningly cheesy at best. Add to that a villain that isn’t particularly menacing, along with attempts at humor that either succeed brilliantly (cat lovers take note) or fall flat and look incredibly lame (as aficionados of musical theater will undoubtedly attest), all of which further add to the picture’s pervasive inconsistency. The inclusion of ample clues for advancing the overarching Marvel Universe storyline continues here, too, furthering a trend that’s growing tiresome in the studio’s releases, a development akin to the “Paul is dead” legacy come to life with every passing picture. Then there’s the trio of heroes themselves, who often appear more like they’ve been plucked from a giddy slumber party flick or a Cyndi Lauper video than taking center stage as seriously empowered champions in an action-adventure offering. All of these failings combine to make this production more of a forgettable placeholder in the Marvel mythology than a standalone feature (not to mention a pale substitute for a sequel to the far-superior film that launched the Captain Marvel franchise in 2019). In short, “The Marvels” is as much of a mess as it is a movie, and that’s troubling for several reasons. It lends credence to the growing criticism that films like this aren’t to be taken seriously. It reinforces the notion that they’re cookie-cutter in nature, easily interchangeable with one another. And it raises questions about the career choices of lead actress Brie Larson, who, though quite capable of playing roles like these, is running the risk of becoming type-cast, a troubling prospect for an Academy Award-winning actress who possesses a depth of talent and is handily adept at taking on better and more serious material than this. In the wake of this release, Marvel Studios should take a step back and seriously assess where its future is headed, especially if movies like this are any indication. As pictures like “Wakanda Forever” (2022) show, the studio is capable of better work – and it’s time to show viewers that.",
      created_at: "2023-11-11T23:49:36.686Z",
      id: "6550131067b61300c84b80e6",
      updated_at: "2023-11-11T23:49:36.801Z",
      url: "https://www.themoviedb.org/review/6550131067b61300c84b80e6",
    },
    {
      author: "Limitedlatency",
      author_details: {
        name: "",
        username: "Limitedlatency",
        avatar_path: null,
        rating: 2,
      },
      content:
        "A trashtastic conclusion to an epic failure of a series of movies. Maybe finally the M-SHE-U can rest in peace and we can get some actual good movies made.",
      created_at: "2023-11-13T19:39:37.144Z",
      id: "65527b79d4fe0400fe049a23",
      updated_at: "2023-11-21T18:07:36.119Z",
      url: "https://www.themoviedb.org/review/65527b79d4fe0400fe049a23",
    },
    {
      author: "photobythomas",
      author_details: {
        name: "",
        username: "photobythomas",
        avatar_path: null,
        rating: 6,
      },
      content:
        "Better than I expected. Go go girl power! Boooo to all the haters!\r\n\r\n66/100",
      created_at: "2023-11-18T23:08:22.662Z",
      id: "655943e6ea84c71096deec0c",
      updated_at: "2023-11-21T15:42:54.588Z",
      url: "https://www.themoviedb.org/review/655943e6ea84c71096deec0c",
    },
    {
      author: "Chandler Danier",
      author_details: {
        name: "Chandler Danier",
        username: "chandlerdanier",
        avatar_path: null,
        rating: 4,
      },
      content:
        "If this movie was 30 minutes I'd have 10 starred it. The rest just kind of falls into the typical colourful, bombastic garbage. Too much Marvel garble. I'm not the target for this by any means but if your kids feel ripped off and angry after watching it, congratulate them and discuss why. Fans of original Star Trek will find something familiar here.",
      created_at: "2024-01-17T14:54:25.694Z",
      id: "65a7ea2105b54900bea829fb",
      updated_at: "2024-01-17T14:54:25.789Z",
      url: "https://www.themoviedb.org/review/65a7ea2105b54900bea829fb",
    },
    {
      author: "pimpskitters",
      author_details: {
        name: "",
        username: "pimpskitters",
        avatar_path: null,
        rating: 3,
      },
      content:
        "Its not just that Larson is deeply uncharismatic, or that now the whole marvel thing reeks of try hard desperation to restart the previous two decades longest running gravy train. Its mostly that all of the marvel movies always have been, low grade cartoons for lame brained adults. The fuckheads who slurped it all are now pretending like this is any worse, it isn't. Its the same thing, and you wasted a lifetime of watching hours on all the other marvel nonsense, you lose.",
      created_at: "2024-01-17T21:21:09.817Z",
      id: "65a844c555c1f40131899d1b",
      updated_at: "2024-01-17T21:21:09.892Z",
      url: "https://www.themoviedb.org/review/65a844c555c1f40131899d1b",
    },
    {
      author: "BornKnight",
      author_details: {
        name: "",
        username: "BornKnight",
        avatar_path: null,
        rating: 6,
      },
      content:
        'Who watched the Mrs. Marvel series already knew the tone the movie would have. It achieves what it wants, and it is fun and cute, not a cinema masterpiece (and it never intended to be). \r\n\r\nOne things that annoys most people are the connections - literally to know much stuff here you needed to be catch up with all the movies and series related on MCU. Also the space between Mrs Marvel are too long to remind of the character.\r\n\r\nNot a "normal" Marvel movie as could be done in a series, but I think the intent was to show to more people the "new" characters and create interest (could be a series).\r\n\r\nScore: 6.0 out of 10.0 / B-.',
      created_at: "2024-01-20T14:24:32.685Z",
      id: "65abd7a085090f00a07def0b",
      updated_at: "2024-01-20T14:24:32.741Z",
      url: "https://www.themoviedb.org/review/65abd7a085090f00a07def0b",
    },
  ],
  backdrops: [
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg",
      vote_average: 5.388,
      vote_count: 4,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1843,
      iso_639_1: null,
      file_path: "/c4apcripPlnlnRcPODgAijCvPul.jpg",
      vote_average: 5.326,
      vote_count: 7,
      width: 3277,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/criPrxkTggCra1jch49jsiSeXo1.jpg",
      vote_average: 5.318,
      vote_count: 3,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/rbWunt3rGCc1U9Jx4WbZqKxmpBe.jpg",
      vote_average: 5.318,
      vote_count: 3,
      width: 3840,
    },
    {
      aspect_ratio: 1.777,
      height: 1688,
      iso_639_1: null,
      file_path: "/rublijezZsTZAyxG090dfhD0IGF.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 3000,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: "en",
      file_path: "/97f3Y0VKFVweh5SZK7KSaTZmJBn.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
      vote_average: 5.286,
      vote_count: 16,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 730,
      iso_639_1: null,
      file_path: "/8ELzhNZCmZbLi20IIXIXwz16ibJ.jpg",
      vote_average: 5.27,
      vote_count: 10,
      width: 1298,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/w9MGuT49AGCMKHbl4kcfXpJkxAQ.jpg",
      vote_average: 5.264,
      vote_count: 8,
      width: 3840,
    },
    {
      aspect_ratio: 1.777,
      height: 1688,
      iso_639_1: null,
      file_path: "/iDoB0DPwrbVFJKVJ9UdpO0WyuyK.jpg",
      vote_average: 5.258,
      vote_count: 6,
      width: 3000,
    },
    {
      aspect_ratio: 1.778,
      height: 1687,
      iso_639_1: null,
      file_path: "/u29P0T9m5l7U1gcNCLMaRSrWwlH.jpg",
      vote_average: 5.258,
      vote_count: 6,
      width: 2999,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/57oimlHZzrmctcWqoz7Ih1ZP6ob.jpg",
      vote_average: 5.258,
      vote_count: 6,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/x1dBfTThFQn3utzRFtlbmqw9crI.jpg",
      vote_average: 5.252,
      vote_count: 4,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/w4pRLYYbhHn3sh9kqRgPZM6GjyS.jpg",
      vote_average: 5.252,
      vote_count: 4,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: "en",
      file_path: "/3AbHZcRdon7TmpqracuQqgJxOGE.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: "en",
      file_path: "/gLnJqNjNJTlo36LsSah4gNIGmzw.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: "en",
      file_path: "/cOOYuvwRMnaHSdQOmldnkjLJ0Jq.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1608,
      iso_639_1: null,
      file_path: "/xiVJ7pK0w5YKidGn2oY8OKiWENl.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2859,
    },
    {
      aspect_ratio: 1.777,
      height: 1688,
      iso_639_1: null,
      file_path: "/7nmIVRbFfJzp1xFhkmvrVFw79kT.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3000,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/czSm2i3uVhqrLA2Qqdz3MEE8bUS.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/JdT3ywizJIICTZCb4dteyCspON.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/oQSmsLq2shCSI5PAqA0xTvxCbYn.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.777,
      height: 1442,
      iso_639_1: null,
      file_path: "/tTKsL5bBZWKUZE2uiyjAxfp6v74.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2562,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: "en",
      file_path: "/72GXhgr70NnFuIDQStIuhWGo2FC.jpg",
      vote_average: 5.238,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/jB48R2vubdLDXmDAbxM1yD9hNCk.jpg",
      vote_average: 5.226,
      vote_count: 15,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1280,
      iso_639_1: null,
      file_path: "/u2C8hDXDc6wmgSKIT5sxarNKulY.jpg",
      vote_average: 5.212,
      vote_count: 11,
      width: 2276,
    },
    {
      aspect_ratio: 1.778,
      height: 1608,
      iso_639_1: null,
      file_path: "/zDgBVONpmfA7fBNVgggGBCGU3Sn.jpg",
      vote_average: 5.206,
      vote_count: 9,
      width: 2859,
    },
    {
      aspect_ratio: 1.778,
      height: 1620,
      iso_639_1: null,
      file_path: "/2o1r5lkILQhmK9DrHDGAowU984P.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 2880,
    },
    {
      aspect_ratio: 1.778,
      height: 1152,
      iso_639_1: null,
      file_path: "/jcd2mgtBiw2dyPvFPFFM9mvgjnQ.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 2048,
    },
    {
      aspect_ratio: 1.778,
      height: 1687,
      iso_639_1: null,
      file_path: "/3Y159IHFiaj2iNdCkPUyqrvzLJ8.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 2999,
    },
    {
      aspect_ratio: 1.778,
      height: 1608,
      iso_639_1: null,
      file_path: "/jm185ApHGWl8tUQU5VkuKwnDIyf.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2859,
    },
    {
      aspect_ratio: 1.778,
      height: 1716,
      iso_639_1: null,
      file_path: "/gHZdXNE0th7xDLI4tWRByKSIReH.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 3051,
    },
    {
      aspect_ratio: 1.778,
      height: 1215,
      iso_639_1: "en",
      file_path: "/o3mMeG4dI9aas4tBEBS5NcG0h6.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2160,
    },
    {
      aspect_ratio: 1.776,
      height: 954,
      iso_639_1: null,
      file_path: "/4ll8rT9KiqS4U1ym81zEXytvSlj.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 1694,
    },
    {
      aspect_ratio: 1.778,
      height: 1608,
      iso_639_1: null,
      file_path: "/5vHvR0fEVuypYZ7TOJTQWPfs3tI.jpg",
      vote_average: 5.156,
      vote_count: 12,
      width: 2859,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/zgpNnim4j70WEHBXCdfIWmFM1Tu.jpg",
      vote_average: 5.106,
      vote_count: 2,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1608,
      iso_639_1: null,
      file_path: "/zINHLGXOonFPkxdD1C47EVNH2MU.jpg",
      vote_average: 5.106,
      vote_count: 2,
      width: 2859,
    },
    {
      aspect_ratio: 1.778,
      height: 1716,
      iso_639_1: null,
      file_path: "/wWjTqbbk7C28e9jWknQUrX5qiQb.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3051,
    },
    {
      aspect_ratio: 1.777,
      height: 1688,
      iso_639_1: null,
      file_path: "/7YbO3fb7B8Z3Kl40uPivWQUPpfg.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3000,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: "en",
      file_path: "/eaoJyhJRkGsbVt0dXMTswsdcDCz.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.781,
      height: 876,
      iso_639_1: null,
      file_path: "/kdozz1mNgYQQUEEg2tQTd3kUyUy.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1560,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/44LMslzl5OuTVALr1UYT8fmZc3T.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 720,
      iso_639_1: null,
      file_path: "/unHCB26PWD3ldjpcJpqWtMFVfE8.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1280,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/yOdYJd1bhHzd4jNx7ZyjXbjUzZb.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/rxhIhVL7PYiOFLsGyv6lfuobFNM.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 2160,
      iso_639_1: null,
      file_path: "/gF4Fu7ZFIchHEWv6zYT2sT2hRGd.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 3840,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/iHGHlRfEb55VAwXW4G51ILMiXQC.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/mjN6tlTvuIZ7PJ8hBheRBAgWRzq.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/9bCbInOF3pywJi88Gy5X1yLcRs8.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/6KD3mNVPTGX9ettvjGyUIOIF5ES.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/wsGey4fJQKcXmhWidGNFunhunrA.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/3FmsNiwM9m7j4P8tWLgxNnYvXcu.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/xqdZRGgdoV1EGvnnX3H1VTNQXls.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/5OPgcMOLxG1Kb34hBcUb7UIxlsc.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1920,
    },
  ],
  posters: [
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
      vote_average: 5.58,
      vote_count: 11,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1755,
      iso_639_1: "en",
      file_path: "/riYDXJzmcOnVTIGzR9HTBSmFgRW.jpg",
      vote_average: 5.522,
      vote_count: 4,
      width: 1170,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/xxh6CFgwzYW29dSOsRjRBTpfqWT.jpg",
      vote_average: 5.454,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/5ee0Myhet6BvFT0NuGHFQ4v1SCJ.jpg",
      vote_average: 5.388,
      vote_count: 4,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/3Jb6cNDPGtPPAsgDGswpbCubqrv.jpg",
      vote_average: 5.384,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/y4YMYsGSMwu8e985g0Zbumvqxld.jpg",
      vote_average: 5.328,
      vote_count: 38,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/hrVdil29WAT9Hrzc1qneBrn6xW9.jpg",
      vote_average: 5.326,
      vote_count: 7,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/ngq5nAVCfjiHB2cBKkqDvLzYMJw.jpg",
      vote_average: 5.318,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.666,
      height: 3000,
      iso_639_1: null,
      file_path: "/as4ephhcxE4sYRh2hLtr38AsBV5.jpg",
      vote_average: 5.318,
      vote_count: 3,
      width: 1999,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/7ZrX2hXJ7vdbZxtWGP6NMenWzom.jpg",
      vote_average: 5.318,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/xJn8zKczW9KSZCFCobbRAbqoAHy.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/rSYtiR0XqtwJxEqHfV2bo1AfmOD.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.666,
      height: 3000,
      iso_639_1: null,
      file_path: "/2c72lUuWJZadYs7RBLHw4uWQIxD.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1999,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/lW7qHsNVo1hBtJugeE8BBJFUJd5.jpg",
      vote_average: 5.292,
      vote_count: 18,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/w1CZDErt2t6qGWhpY62tkpbtYEc.jpg",
      vote_average: 5.286,
      vote_count: 16,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2048,
      iso_639_1: "en",
      file_path: "/yfP6vnRJo6anTqtHjYwYcYlNvUN.jpg",
      vote_average: 5.258,
      vote_count: 6,
      width: 1365,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/r3CfX9dLoSH4CtUZw99VVzyEhle.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/dPRmltWty1rUJQ1yqwn6S7zRKRB.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/1mxOcBBB4nPVn5XIReoiFOEFTwn.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/yleHguaF1OknBTYk9rTTHYvsiap.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/v1FTINtyPQfo3O2YURqNthqvyMc.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.751,
      height: 1253,
      iso_639_1: "en",
      file_path: "/vcuYWKOONDTxkIv9O0kzCU2fQKi.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 941,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/8ZtcAErmQJRS8FpS7GvrSiX2q0Q.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/tUtgLOESpCx7ue4BaeCTqp3vn1b.jpg",
      vote_average: 5.238,
      vote_count: 19,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/8j7Qnegy40bscZUx2zJohkonaty.jpg",
      vote_average: 5.228,
      vote_count: 34,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/c41BcrlDJUgoOU1ogbg4K6WrdQy.jpg",
      vote_average: 5.226,
      vote_count: 15,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/wCVGHgW9qAhwVGbQxl6lMEmYFhR.jpg",
      vote_average: 5.22,
      vote_count: 13,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2048,
      iso_639_1: "en",
      file_path: "/rp3cjGabBAVpZtKyY4jiwikzj3H.jpg",
      vote_average: 5.194,
      vote_count: 22,
      width: 1365,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/eb9ZWCBiJbKSvDNS9dBrE8C5YZg.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/nU5Nxbo3KbuFKy7O8hAP1xK1jsO.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/fXWinGtbW5QPZQ0DsyMhjOekm1N.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 2000,
    },
    {
      aspect_ratio: 0.673,
      height: 1909,
      iso_639_1: "en",
      file_path: "/7mUl9KCaQYGo3s1MSWNhXktBJDt.jpg",
      vote_average: 5.186,
      vote_count: 20,
      width: 1284,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/6ZFhywcMqqWL3wlokeTMALrmmUB.jpg",
      vote_average: 5.186,
      vote_count: 20,
      width: 2000,
    },
    {
      aspect_ratio: 0.675,
      height: 2500,
      iso_639_1: null,
      file_path: "/qXQfdhhBMg1aney14KY18jV9n72.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1688,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/jdXiaj4EDnJgpCJPDMEroktXmNE.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/zlDhEP2TMxpsTuoSXw7Zefm9u4.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/roqa4ywYfZYA9B4WfbTGGgoddiX.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/wiSoQgICJyVZ4spZcEVhNfNOht8.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/Ncy6shbw0Q7ZaxmHwSAFGsPlLW.jpg",
      vote_average: 5.18,
      vote_count: 18,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/bW7ntqpNBr9TEB3oBL9LRGHeImR.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/85c1UkH4zhXuadchA3aRmtapfqX.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/43I2VdReurhhLo4nR3l9pi83UYJ.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/s2aj8kSvQCR4eoQtQTCqNPyAV7r.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/AiXSeO6r3HGtEqxstfCptO3k1N9.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 1245,
      iso_639_1: "en",
      file_path: "/jE1eH6xrLhimcHjkHPVNZnBfELo.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 830,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/mq62ZM7gdb6nHM2KLenm6iqlU1z.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.666,
      height: 1346,
      iso_639_1: "en",
      file_path: "/n396UXzRx9T5uydJgkfZNMgXZb7.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 897,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/3sXv15ymVkaV7E18m4TlTgwNkAN.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/dlKyjtZenxisSYxYmif4xlQRNKD.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/2rEwwC3HykGvqQiGXUTDGeygHlI.jpg",
      vote_average: 5.172,
      vote_count: 16,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/u8n4EXxCy6U0WAMgcDHwxH6kTyY.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/psOIVY080klJlTX3sQUD8SqfdRb.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/2xoXdRy30zVvx1PT9jUgcA36syp.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/oxnKRy7IGRYZP86eLaRujHUVhae.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/bgTSGqUqxr2Rj41XR9ghifJTmDc.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/hdNh5eyAYk9hZAU5D7sRMa0XslH.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1789,
      iso_639_1: "en",
      file_path: "/wNUrYCepOhj2Mrnc81Y5kixKyb9.jpg",
      vote_average: 5.156,
      vote_count: 12,
      width: 1193,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/zp4xU0RO6DNk4TSHPxo2uFb08jb.jpg",
      vote_average: 5.146,
      vote_count: 10,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/matHJ4WeTYC5dem9WmvZ8QYvCHI.jpg",
      vote_average: 5.138,
      vote_count: 8,
      width: 2000,
    },
    {
      aspect_ratio: 0.675,
      height: 2500,
      iso_639_1: "en",
      file_path: "/5qyBA1knf8XaOZB9luChLvEgvVP.jpg",
      vote_average: 5.128,
      vote_count: 6,
      width: 1688,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/mka3WJ5gDlib7ouGZycZBC8PASv.jpg",
      vote_average: 5.128,
      vote_count: 6,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 1143,
      iso_639_1: "en",
      file_path: "/82RnRinCd9rRkOrSA71TEvLzgIK.jpg",
      vote_average: 5.118,
      vote_count: 4,
      width: 762,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/mYtGqsxuUsnXNY5tTcVpxzc4gMD.jpg",
      vote_average: 5.106,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/95dSBqo7fn2UNdzxQU6Zwl8SQTB.jpg",
      vote_average: 5.106,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/pbeK8zvKq2h1FGHkgC8ADUnk9uR.jpg",
      vote_average: 5.068,
      vote_count: 7,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/lWAPRTO3nNIWlifUr5POuVuiePT.jpg",
      vote_average: 5.056,
      vote_count: 5,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/njwIGzlNGSfxCy6QeQnz1G6qrat.jpg",
      vote_average: 5.056,
      vote_count: 5,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/9juYvUXLlwjsk8o0RLv6pWdFRvn.jpg",
      vote_average: 5.046,
      vote_count: 14,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/6UMIiVyfyfr0h2Xdpq7zMGc7Woo.jpg",
      vote_average: 5.044,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/gDKFgKip3MWFvBk0JNmzghmqN8A.jpg",
      vote_average: 4.996,
      vote_count: 6,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 1576,
      iso_639_1: "en",
      file_path: "/qLFJmnMoOAelnNcXinmhEzEcYAw.jpg",
      vote_average: 4.996,
      vote_count: 6,
      width: 1051,
    },
    {
      aspect_ratio: 0.675,
      height: 2500,
      iso_639_1: "en",
      file_path: "/geJv3ebAeE0CT0nCdYCl8PozFWE.jpg",
      vote_average: 4.954,
      vote_count: 9,
      width: 1688,
    },
    {
      aspect_ratio: 0.667,
      height: 1350,
      iso_639_1: "en",
      file_path: "/cq7X9nx0VzAatIBQ8S6GafuX23B.jpg",
      vote_average: 4.954,
      vote_count: 9,
      width: 900,
    },
    {
      aspect_ratio: 0.667,
      height: 900,
      iso_639_1: "en",
      file_path: "/bnz17wOkp9O0c9JADOncEx0Q1sJ.jpg",
      vote_average: 4.928,
      vote_count: 14,
      width: 600,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/soUPwv2xryF9BFDvwCBzRbfSFA1.jpg",
      vote_average: 4.882,
      vote_count: 8,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/vmydiA2MKEC5trvDcH3seHwa5ny.jpg",
      vote_average: 4.81,
      vote_count: 7,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 2048,
      iso_639_1: "en",
      file_path: "/gWxeVJ920nprJEbXbzmuuzeaAar.jpg",
      vote_average: 4.774,
      vote_count: 10,
      width: 1365,
    },
    {
      aspect_ratio: 0.667,
      height: 2500,
      iso_639_1: "en",
      file_path: "/g4I7WSBwRsR93AgADUyYVqfQo4B.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1667,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/fKLqgP1LKayXXceSzKXX403lA3C.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/sU74ZjJQkPE4Srl55gdX3wMh8uH.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.666,
      height: 1929,
      iso_639_1: "en",
      file_path: "/gReEsOnk7FhgQ76XYMBzINf661v.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1285,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/ieHRSyDEDjS6FkEhFFNRi5XlKNE.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/g80QWcS8YBR8atv3PrYPrQ2RjVG.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/AjOZZIKFg2mmWSBNWHvAgItTbCq.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/3PjXPAkrVrcY4VXFOE9vJjmU6YW.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.706,
      height: 1000,
      iso_639_1: "en",
      file_path: "/49AmKQbzQrLCI039r9x6O9EihzM.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 706,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/beFiSACtVm5wDo8qYkjP3z2NvNJ.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/eRxfcyRlxzIxmIcEsldWeFzpgvk.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1000,
      iso_639_1: "en",
      file_path: "/3EpQCAKACWP7RYPtAyKQRqaer7e.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 667,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: null,
      file_path: "/6E50Y1UgLyCa6y4uF05kRfDrOod.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1000,
    },
    {
      aspect_ratio: 0.662,
      height: 2235,
      iso_639_1: "en",
      file_path: "/mabL3MWMxYwMlYyrPHCebRoSp6.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1480,
    },
    {
      aspect_ratio: 0.666,
      height: 2234,
      iso_639_1: "en",
      file_path: "/b7sCAmCy0j1CgsiTVAtEK2eXDFH.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1488,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/fDbZd7mKgMTQMtzrnNpGGNK6uiY.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/mtoNUSeLvTs6soxfxvRxaFiDe7L.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1000,
      iso_639_1: "en",
      file_path: "/5yDmvy0bW8X1GMAAgXu3PAKidCi.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 667,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/Ah1IsFd0wdoJLh55vbMatas1wzh.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/iSl09Vu7sMrq4PotOcwDYSESv6F.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/glE6Rm5LzO0JwKQlu8aqZhadkBi.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/voNXeIsxu2OBdThPUvqGxVRGd0L.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 900,
      iso_639_1: "en",
      file_path: "/keYhG13hDNr0pzBSEgmaAoVJDGW.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 600,
    },
    {
      aspect_ratio: 0.667,
      height: 1800,
      iso_639_1: "en",
      file_path: "/imCljrBBdbE95KGHijlLO53tFGi.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 1200,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/5uIV0pkItPJBXXoCity7kWMPBek.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/bzop4R3QgbqG8bGvLqEHev2XK3E.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 2000,
    },
    {
      aspect_ratio: 0.679,
      height: 1002,
      iso_639_1: "en",
      file_path: "/1VqFaO3T62g3AbySZ0KKsTgwmt8.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 680,
    },
    {
      aspect_ratio: 0.679,
      height: 1002,
      iso_639_1: "en",
      file_path: "/ko569cVVUnPkZV0oV69H1cBdY3A.jpg",
      vote_average: 0,
      vote_count: 0,
      width: 680,
    },
  ],
  recommendations: [
    {
      adult: false,
      backdrop_path: "/kHlX3oqdD4VGaLpB8O78M25KfdS.jpg",
      id: 945729,
      title: "A Haunting in Venice",
      original_language: "en",
      original_title: "A Haunting in Venice",
      overview:
        "Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.",
      poster_path: "/l6iwxT0NbVw6QiF08YTIuTnXS82.jpg",
      media_type: "movie",
      genre_ids: [9648, 53, 80],
      popularity: 48.208,
      release_date: "2023-09-13",
      video: false,
      vote_average: 6.739,
      vote_count: 1720,
    },
    {
      adult: false,
      backdrop_path: "/e0M3WVJm4nBrAg0LbJq0gdKi3U7.jpg",
      id: 695721,
      title: "The Hunger Games: The Ballad of Songbirds & Snakes",
      original_language: "en",
      original_title: "The Hunger Games: The Ballad of Songbirds & Snakes",
      overview:
        "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
      poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
      media_type: "movie",
      genre_ids: [18, 878, 28],
      popularity: 368.018,
      release_date: "2023-11-15",
      video: false,
      vote_average: 7.224,
      vote_count: 1581,
    },
    {
      adult: false,
      backdrop_path: "/tj7mp7uWjVw5N73G5Hwm1bkMOcD.jpg",
      id: 975902,
      title: "Boudica",
      original_language: "en",
      original_title: "Boudica",
      overview:
        "Inspired by events in A.D. 60, Boudica follows the eponymous Celtic warrior who rules the Iceni people alongside her husband Prasutagus. When he dies at the hands of Roman soldiers, Boudica’s kingdom is left without a male heir and the Romans seize her land and property.  Driven to the edge of madness and determined to avenge her husband’s death, Boudica rallies the various tribes from the region and wages an epic war against the mighty Roman empire.",
      poster_path: "/ssEFC5wfFjj7lJpUgwJDOK1Xu1J.jpg",
      media_type: "movie",
      genre_ids: [28, 10752],
      popularity: 65.797,
      release_date: "2023-10-26",
      video: false,
      vote_average: 5.911,
      vote_count: 101,
    },
    {
      adult: false,
      backdrop_path: "/7NRGAtu8E4343NSKwhkgmVRDINw.jpg",
      id: 507089,
      title: "Five Nights at Freddy's",
      original_language: "en",
      original_title: "Five Nights at Freddy's",
      overview:
        "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
      poster_path: "/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
      media_type: "movie",
      genre_ids: [27, 9648],
      popularity: 293.53,
      release_date: "2023-10-25",
      video: false,
      vote_average: 7.7,
      vote_count: 3251,
    },
    {
      adult: false,
      backdrop_path: null,
      id: 410402,
      title: "Rater RajaniGandha",
      original_language: "bn",
      original_title: "রাতের রজনীগন্ধা",
      overview:
        "A novelist, Rahul, meets Jui and is allured by the way her life shapes up. Played by Rituparna Sengupta, Jui takes a huge step by moving to Kolkata following the demise of her parents. While in Kolkata, she begins to work as a bar singer in the city and there she meets Rajesh Sharma. The two get married, however, things get worse for her as she is forced into the world of prostitution and goes on to become an escort. Rahul, a novelist, meets her and pens her entire story which is very different from that of an ordinary girl.",
      poster_path: null,
      media_type: "movie",
      genre_ids: [],
      popularity: 1.491,
      release_date: "2016-01-01",
      video: false,
      vote_average: 10,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/sMfWv9eaacE4yHueu2Hq15JeONi.jpg",
      id: 44276,
      title: "The Wizard of Speed and Time",
      original_language: "en",
      original_title: "The Wizard of Speed and Time",
      overview:
        "A Hollywood filmmaker (Mike Jittlov) makes a short for an evil film studio. Unbeknownst to him, the producer has placed a bet of $25,000 that he won't come up with anything with a use. Luckily, our film creator gets the help of his friends.",
      poster_path: "/gByaD1XpPqKubDgvA4m356n6EKV.jpg",
      media_type: "movie",
      genre_ids: [18, 35, 12],
      popularity: 2.687,
      release_date: "1989-09-22",
      video: false,
      vote_average: 6.269,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
      id: 575264,
      title: "Mission: Impossible - Dead Reckoning Part One",
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
      poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
      media_type: "movie",
      genre_ids: [28, 53],
      popularity: 210.037,
      release_date: "2023-07-08",
      video: false,
      vote_average: 7.578,
      vote_count: 2960,
    },
    {
      adult: false,
      backdrop_path: "/su7FqHdZez0oOvpZAbV7P6BGq0R.jpg",
      id: 939335,
      title: "Muzzle",
      original_language: "en",
      original_title: "Muzzle",
      overview:
        "LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.",
      poster_path: "/AsM1H8DfaNo7bRu4q76MaVRRbIY.jpg",
      media_type: "movie",
      genre_ids: [28, 80, 18, 53],
      popularity: 123.125,
      release_date: "2023-09-29",
      video: false,
      vote_average: 6.584,
      vote_count: 148,
    },
    {
      adult: false,
      backdrop_path: "/f9Atch0jlzcOT9RbF8UccqfNOpd.jpg",
      id: 800158,
      title: "The Killer",
      original_language: "en",
      original_title: "The Killer",
      overview:
        "After a fateful near-miss, an assassin battles his employers, and himself, on an international manhunt he insists isn't personal.",
      poster_path: "/e7Jvsry47JJQruuezjU2X1Z6J77.jpg",
      media_type: "movie",
      genre_ids: [80, 53],
      popularity: 55.381,
      release_date: "2023-10-25",
      video: false,
      vote_average: 6.616,
      vote_count: 1543,
    },
    {
      adult: false,
      backdrop_path: "/uUJp5I4IbzuhdUiEx4R9OAoFpbz.jpg",
      id: 951491,
      title: "Saw X",
      original_language: "en",
      original_title: "Saw X",
      overview:
        "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
      poster_path: "/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
      media_type: "movie",
      genre_ids: [27, 53, 9648],
      popularity: 143.156,
      release_date: "2023-09-27",
      video: false,
      vote_average: 7.4,
      vote_count: 1439,
    },
    {
      adult: false,
      backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      id: 678512,
      title: "Sound of Freedom",
      original_language: "en",
      original_title: "Sound of Freedom",
      overview:
        "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
      poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
      media_type: "movie",
      genre_ids: [28, 18],
      popularity: 226.556,
      release_date: "2023-07-03",
      video: false,
      vote_average: 8.051,
      vote_count: 1841,
    },
    {
      adult: false,
      backdrop_path: "/nVcArEXbaCOldQZo8ssv3Yfe9F5.jpg",
      id: 1047016,
      title: "The Commander",
      original_language: "it",
      original_title: "Comandante",
      overview:
        "One dark night during the early phases of WWII, the Italian Royal Navy submarine Cappellini sinks an armed merchant ship sailing with lights out. At that moment, its commander Salvatore Todaro makes a decision that was destined to go down in history: to save the 26 shipwrecked Belgians who otherwise would have drowned in the middle of the Atlantic Ocean and disembark them at the nearest safe harbor. To make room for them on board his submarine, he is forced to navigate on the surface of the water for three days, visible to the enemy forces and endangering his life and that of his men.",
      poster_path: "/biTOtPfIvLI4dbT2uJedyoFAjVm.jpg",
      media_type: "movie",
      genre_ids: [18, 36, 10752],
      popularity: 8.67,
      release_date: "2023-10-31",
      video: false,
      vote_average: 7.181,
      vote_count: 58,
    },
    {
      adult: false,
      backdrop_path: "/50stq3Jlny6oEgJjsXbQvbajCNw.jpg",
      id: 1020006,
      title: "Priscilla",
      original_language: "en",
      original_title: "Priscilla",
      overview:
        "When teenage Priscilla Beaulieu meets Elvis Presley at a party, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments: a thrilling crush, an ally in loneliness, a vulnerable best friend.",
      poster_path: "/uDCeELWWpsNq7ErM61Yuq70WAE9.jpg",
      media_type: "movie",
      genre_ids: [10749, 18],
      popularity: 141.477,
      release_date: "2023-10-27",
      video: false,
      vote_average: 7,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg",
      id: 840430,
      title: "The Holdovers",
      original_language: "en",
      original_title: "The Holdovers",
      overview:
        "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.",
      poster_path: "/VHSzNBTwxV8vh7wylo7O9CLdac.jpg",
      media_type: "movie",
      genre_ids: [35, 18],
      popularity: 159.662,
      release_date: "2023-10-27",
      video: false,
      vote_average: 7.7,
      vote_count: 524,
    },
    {
      adult: false,
      backdrop_path: "/hb0BeFvZNx2zLGWwuwENOIVeK1U.jpg",
      id: 792293,
      title: "Dumb Money",
      original_language: "en",
      original_title: "Dumb Money",
      overview:
        "Vlogger Keith Gill sinks his life savings into GameStop stock and posts about it. When social media starts blowing up, so do his life and the lives of everyone following him. As a stock tip becomes a movement, everyone gets rich—until the billionaires fight back, and both sides find their worlds turned upside down.",
      poster_path: "/bqs4TeKFbfkcbQbuGAuKYu82tnp.jpg",
      media_type: "movie",
      genre_ids: [35, 18, 36],
      popularity: 43.975,
      release_date: "2023-09-15",
      video: false,
      vote_average: 6.713,
      vote_count: 237,
    },
    {
      adult: false,
      backdrop_path: "/7zmauCUkwjq9wBWBY1IoV5mi8ju.jpg",
      id: 1044648,
      title: "Nuovo Olimpo",
      original_language: "it",
      original_title: "Nuovo Olimpo",
      overview:
        "In 1970s Rome, a casual encounter between Enea and Pietro at a movie theater turns into an unforgettable romance — until destiny pulls them apart.",
      poster_path: "/3nx8pSvAARYOLlZ2MNBlH7vW9jv.jpg",
      media_type: "movie",
      genre_ids: [10749, 18],
      popularity: 22.267,
      release_date: "2023-11-01",
      video: false,
      vote_average: 6.86,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: "/oFSQEG1lJTTISj3QKB7cJ9ANkFw.jpg",
      id: 1154598,
      title: "LEGO Marvel Avengers: Code Red",
      original_language: "en",
      original_title: "LEGO Marvel Avengers: Code Red",
      overview:
        "The Avengers gather to celebrate their latest victory, but their celebration is quickly interrupted by the mysterious disappearance of Black Widow's father, Red Guardian. As the Avengers investigate, they discover that Red Guardian isn't the only one missing when they meet a dangerous new foe quite unlike anything they've ever encountered before.",
      poster_path: "/rDzig50dj7VpLwJ7SThbamETK1G.jpg",
      media_type: "movie",
      genre_ids: [16, 28, 10751],
      popularity: 36.82,
      release_date: "2023-10-26",
      video: false,
      vote_average: 6.443,
      vote_count: 61,
    },
    {
      adult: false,
      backdrop_path: "/zgQQF04u3OgNBJqClRNby1FPz9s.jpg",
      id: 893723,
      title: "PAW Patrol: The Mighty Movie",
      original_language: "en",
      original_title: "PAW Patrol: The Mighty Movie",
      overview:
        "A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.",
      poster_path: "/aTvePCU7exLepwg5hWySjwxojQK.jpg",
      media_type: "movie",
      genre_ids: [16, 10751, 28, 878, 35, 18, 12],
      popularity: 200.511,
      release_date: "2023-09-21",
      video: false,
      vote_average: 7.05,
      vote_count: 302,
    },
    {
      adult: false,
      backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
      id: 897087,
      title: "Freelance",
      original_language: "en",
      original_title: "Freelance",
      overview:
        "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
      poster_path: "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
      media_type: "movie",
      genre_ids: [28, 35],
      popularity: 284.383,
      release_date: "2023-10-05",
      video: false,
      vote_average: 6.5,
      vote_count: 484,
    },
    {
      adult: false,
      backdrop_path: "/2n6KECWCNmekIEgZFNlldkELUsP.jpg",
      id: 997391,
      title: "RDX: Robert Dony Xavier",
      original_language: "ml",
      original_title: "ആര്‍ഡിഎക്സ്: റോബര്‍ട്ട് ഡോണി സേവ്യര്‍",
      overview:
        "Once-menacing, anger fueled, trained martial arts fighters Robert, Dony and Xavier settle down to peaceful lives, after a significant event prompts them. Fate orchestrates their reunion and return from exile to their fighting ways, when their history linger ominously and one of them faces a violent attack.",
      poster_path: "/E4prGNIMN8USgwZBkVj3ADasAG.jpg",
      media_type: "movie",
      genre_ids: [28, 18],
      popularity: 37.142,
      release_date: "2023-08-25",
      video: false,
      vote_average: 7.1,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/4xeVGvJ4PrIkGs61QNwg7c3Jlns.jpg",
      id: 1064024,
      title: "Locked In",
      original_language: "en",
      original_title: "Locked In",
      overview:
        "A kindly nurse tries to unlock the secrets of a coma patient's injuries — and discovers the bitter rivalry, infidelity, betrayal and murder behind them.",
      poster_path: "/blQaj6biyBMLo34cuFKKwbgjIBz.jpg",
      media_type: "movie",
      genre_ids: [53],
      popularity: 37.558,
      release_date: "2023-11-01",
      video: false,
      vote_average: 5.513,
      vote_count: 151,
    },
  ],
  releaseYear: 2023,
  releaseDate: "Nov 8",
  status: "Released",
  crewData: [
    {
      adult: false,
      gender: 1,
      id: 1795072,
      known_for_department: "Directing",
      name: "Nia DaCosta",
      original_name: "Nia DaCosta",
      popularity: 12.328,
      profile_path: "/jgzkYRpkNDa9KTX8WmhdMOIEVaX.jpg",
      credit_id: "5f2b457af1759c00378956db",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 1,
      id: 1795072,
      known_for_department: "Directing",
      name: "Nia DaCosta",
      original_name: "Nia DaCosta",
      popularity: 12.328,
      profile_path: "/jgzkYRpkNDa9KTX8WmhdMOIEVaX.jpg",
      credit_id: "64b8bb1b4d23dd00ad0cda4b",
      department: "Writing",
      job: "Writer",
    },
    {
      adult: false,
      gender: 1,
      id: 2056482,
      known_for_department: "Writing",
      name: "Megan McDonnell",
      original_name: "Megan McDonnell",
      popularity: 4.988,
      profile_path: "/vELF848DajPGmu46LXT51JOlhYs.jpg",
      credit_id: "64b8bb151685da00acaf0822",
      department: "Writing",
      job: "Writer",
    },
    {
      adult: false,
      gender: 1,
      id: 3119329,
      known_for_department: "Writing",
      name: "Elissa Karasik",
      original_name: "Elissa Karasik",
      popularity: 3.976,
      profile_path: null,
      credit_id: "64b8bb28ab684900ad8c48e0",
      department: "Writing",
      job: "Writer",
    },
  ],
};
